/*
 * generated by Xtext 2.27.0
 */
package org.ftn.domij.securitydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class SecurityDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ApplicationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ftn.domij.securitydsl.SecurityDsl.Application");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cApplicationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cApplicationKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cNameKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameEStringParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDatabaseKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cApp_databaseAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cApp_databaseDatabaseParserRuleCall_5_1_0 = (RuleCall)cApp_databaseAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cSecurityKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cApp_securityAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cApp_securitySecurityParserRuleCall_6_1_0 = (RuleCall)cApp_securityAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cModelKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Group cGroup_7_1 = (Group)cGroup_7.eContents().get(1);
		private final Keyword cUserKeyword_7_1_0 = (Keyword)cGroup_7_1.eContents().get(0);
		private final Assignment cApp_modelsAssignment_7_1_1 = (Assignment)cGroup_7_1.eContents().get(1);
		private final RuleCall cApp_modelsUserParserRuleCall_7_1_1_0 = (RuleCall)cApp_modelsAssignment_7_1_1.eContents().get(0);
		private final Group cGroup_7_2 = (Group)cGroup_7.eContents().get(2);
		private final Keyword cRoleKeyword_7_2_0 = (Keyword)cGroup_7_2.eContents().get(0);
		private final Assignment cApp_modelsAssignment_7_2_1 = (Assignment)cGroup_7_2.eContents().get(1);
		private final RuleCall cApp_modelsRoleParserRuleCall_7_2_1_0 = (RuleCall)cApp_modelsAssignment_7_2_1.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cOtherKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_7_3_1 = (Keyword)cGroup_7_3.eContents().get(1);
		private final Assignment cApp_modelsAssignment_7_3_2 = (Assignment)cGroup_7_3.eContents().get(2);
		private final RuleCall cApp_modelsOtherModelParserRuleCall_7_3_2_0 = (RuleCall)cApp_modelsAssignment_7_3_2.eContents().get(0);
		private final Group cGroup_7_3_3 = (Group)cGroup_7_3.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_3_0 = (Keyword)cGroup_7_3_3.eContents().get(0);
		private final Assignment cApp_modelsAssignment_7_3_3_1 = (Assignment)cGroup_7_3_3.eContents().get(1);
		private final RuleCall cApp_modelsOtherModelParserRuleCall_7_3_3_1_0 = (RuleCall)cApp_modelsAssignment_7_3_3_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_7_3_4 = (Keyword)cGroup_7_3.eContents().get(4);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cControllersKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Group cGroup_8_1 = (Group)cGroup_8.eContents().get(1);
		private final Keyword cAuthKeyword_8_1_0 = (Keyword)cGroup_8_1.eContents().get(0);
		private final Assignment cApp_controllersAssignment_8_1_1 = (Assignment)cGroup_8_1.eContents().get(1);
		private final RuleCall cApp_controllersAuthenticationParserRuleCall_8_1_1_0 = (RuleCall)cApp_controllersAssignment_8_1_1.eContents().get(0);
		private final Group cGroup_8_2 = (Group)cGroup_8.eContents().get(2);
		private final Keyword cOtherKeyword_8_2_0 = (Keyword)cGroup_8_2.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_8_2_1 = (Keyword)cGroup_8_2.eContents().get(1);
		private final Assignment cApp_controllersAssignment_8_2_2 = (Assignment)cGroup_8_2.eContents().get(2);
		private final RuleCall cApp_controllersOtherControllerParserRuleCall_8_2_2_0 = (RuleCall)cApp_controllersAssignment_8_2_2.eContents().get(0);
		private final Group cGroup_8_2_3 = (Group)cGroup_8_2.eContents().get(3);
		private final Keyword cCommaKeyword_8_2_3_0 = (Keyword)cGroup_8_2_3.eContents().get(0);
		private final Assignment cApp_controllersAssignment_8_2_3_1 = (Assignment)cGroup_8_2_3.eContents().get(1);
		private final RuleCall cApp_controllersOtherControllerParserRuleCall_8_2_3_1_0 = (RuleCall)cApp_controllersAssignment_8_2_3_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_8_2_4 = (Keyword)cGroup_8_2.eContents().get(4);
		
		//Application returns Application:
		//    {Application}
		//    'application:'
		//     'name:' name=EString
		//    ( 'description:' description=EString )?
		//    ('database:'  app_database=Database)?
		//    ('security:' app_security=Security)?
		//    ('model:'
		//        ('user:' app_models+=User)?
		//        ('role:' app_models+=Role)?
		//        ('other:' '[' app_models+=OtherModel ( "," app_models+=OtherModel )* ']')?
		//    )?
		//    ('controllers:'
		//        ('auth:' app_controllers+=Authentication)?
		//        ('other:' '[' app_controllers+=OtherController ( "," app_controllers+=OtherController )* ']')?
		//    )?;
		@Override public ParserRule getRule() { return rule; }
		
		//{Application}
		//'application:'
		// 'name:' name=EString
		//( 'description:' description=EString )?
		//('database:'  app_database=Database)?
		//('security:' app_security=Security)?
		//('model:'
		//    ('user:' app_models+=User)?
		//    ('role:' app_models+=Role)?
		//    ('other:' '[' app_models+=OtherModel ( "," app_models+=OtherModel )* ']')?
		//)?
		//('controllers:'
		//    ('auth:' app_controllers+=Authentication)?
		//    ('other:' '[' app_controllers+=OtherController ( "," app_controllers+=OtherController )* ']')?
		//)?
		public Group getGroup() { return cGroup; }
		
		//{Application}
		public Action getApplicationAction_0() { return cApplicationAction_0; }
		
		//'application:'
		public Keyword getApplicationKeyword_1() { return cApplicationKeyword_1; }
		
		//'name:'
		public Keyword getNameKeyword_2() { return cNameKeyword_2; }
		
		//name=EString
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_3_0() { return cNameEStringParserRuleCall_3_0; }
		
		//( 'description:' description=EString )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'description:'
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_1_0() { return cDescriptionEStringParserRuleCall_4_1_0; }
		
		//('database:'  app_database=Database)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'database:'
		public Keyword getDatabaseKeyword_5_0() { return cDatabaseKeyword_5_0; }
		
		//app_database=Database
		public Assignment getApp_databaseAssignment_5_1() { return cApp_databaseAssignment_5_1; }
		
		//Database
		public RuleCall getApp_databaseDatabaseParserRuleCall_5_1_0() { return cApp_databaseDatabaseParserRuleCall_5_1_0; }
		
		//('security:' app_security=Security)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'security:'
		public Keyword getSecurityKeyword_6_0() { return cSecurityKeyword_6_0; }
		
		//app_security=Security
		public Assignment getApp_securityAssignment_6_1() { return cApp_securityAssignment_6_1; }
		
		//Security
		public RuleCall getApp_securitySecurityParserRuleCall_6_1_0() { return cApp_securitySecurityParserRuleCall_6_1_0; }
		
		//('model:'
		//    ('user:' app_models+=User)?
		//    ('role:' app_models+=Role)?
		//    ('other:' '[' app_models+=OtherModel ( "," app_models+=OtherModel )* ']')?
		//)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'model:'
		public Keyword getModelKeyword_7_0() { return cModelKeyword_7_0; }
		
		//('user:' app_models+=User)?
		public Group getGroup_7_1() { return cGroup_7_1; }
		
		//'user:'
		public Keyword getUserKeyword_7_1_0() { return cUserKeyword_7_1_0; }
		
		//app_models+=User
		public Assignment getApp_modelsAssignment_7_1_1() { return cApp_modelsAssignment_7_1_1; }
		
		//User
		public RuleCall getApp_modelsUserParserRuleCall_7_1_1_0() { return cApp_modelsUserParserRuleCall_7_1_1_0; }
		
		//('role:' app_models+=Role)?
		public Group getGroup_7_2() { return cGroup_7_2; }
		
		//'role:'
		public Keyword getRoleKeyword_7_2_0() { return cRoleKeyword_7_2_0; }
		
		//app_models+=Role
		public Assignment getApp_modelsAssignment_7_2_1() { return cApp_modelsAssignment_7_2_1; }
		
		//Role
		public RuleCall getApp_modelsRoleParserRuleCall_7_2_1_0() { return cApp_modelsRoleParserRuleCall_7_2_1_0; }
		
		//('other:' '[' app_models+=OtherModel ( "," app_models+=OtherModel )* ']')?
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//'other:'
		public Keyword getOtherKeyword_7_3_0() { return cOtherKeyword_7_3_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_7_3_1() { return cLeftSquareBracketKeyword_7_3_1; }
		
		//app_models+=OtherModel
		public Assignment getApp_modelsAssignment_7_3_2() { return cApp_modelsAssignment_7_3_2; }
		
		//OtherModel
		public RuleCall getApp_modelsOtherModelParserRuleCall_7_3_2_0() { return cApp_modelsOtherModelParserRuleCall_7_3_2_0; }
		
		//( "," app_models+=OtherModel )*
		public Group getGroup_7_3_3() { return cGroup_7_3_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_3_0() { return cCommaKeyword_7_3_3_0; }
		
		//app_models+=OtherModel
		public Assignment getApp_modelsAssignment_7_3_3_1() { return cApp_modelsAssignment_7_3_3_1; }
		
		//OtherModel
		public RuleCall getApp_modelsOtherModelParserRuleCall_7_3_3_1_0() { return cApp_modelsOtherModelParserRuleCall_7_3_3_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_7_3_4() { return cRightSquareBracketKeyword_7_3_4; }
		
		//('controllers:'
		//    ('auth:' app_controllers+=Authentication)?
		//    ('other:' '[' app_controllers+=OtherController ( "," app_controllers+=OtherController )* ']')?
		//)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'controllers:'
		public Keyword getControllersKeyword_8_0() { return cControllersKeyword_8_0; }
		
		//('auth:' app_controllers+=Authentication)?
		public Group getGroup_8_1() { return cGroup_8_1; }
		
		//'auth:'
		public Keyword getAuthKeyword_8_1_0() { return cAuthKeyword_8_1_0; }
		
		//app_controllers+=Authentication
		public Assignment getApp_controllersAssignment_8_1_1() { return cApp_controllersAssignment_8_1_1; }
		
		//Authentication
		public RuleCall getApp_controllersAuthenticationParserRuleCall_8_1_1_0() { return cApp_controllersAuthenticationParserRuleCall_8_1_1_0; }
		
		//('other:' '[' app_controllers+=OtherController ( "," app_controllers+=OtherController )* ']')?
		public Group getGroup_8_2() { return cGroup_8_2; }
		
		//'other:'
		public Keyword getOtherKeyword_8_2_0() { return cOtherKeyword_8_2_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_8_2_1() { return cLeftSquareBracketKeyword_8_2_1; }
		
		//app_controllers+=OtherController
		public Assignment getApp_controllersAssignment_8_2_2() { return cApp_controllersAssignment_8_2_2; }
		
		//OtherController
		public RuleCall getApp_controllersOtherControllerParserRuleCall_8_2_2_0() { return cApp_controllersOtherControllerParserRuleCall_8_2_2_0; }
		
		//( "," app_controllers+=OtherController )*
		public Group getGroup_8_2_3() { return cGroup_8_2_3; }
		
		//","
		public Keyword getCommaKeyword_8_2_3_0() { return cCommaKeyword_8_2_3_0; }
		
		//app_controllers+=OtherController
		public Assignment getApp_controllersAssignment_8_2_3_1() { return cApp_controllersAssignment_8_2_3_1; }
		
		//OtherController
		public RuleCall getApp_controllersOtherControllerParserRuleCall_8_2_3_1_0() { return cApp_controllersOtherControllerParserRuleCall_8_2_3_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_8_2_4() { return cRightSquareBracketKeyword_8_2_4; }
	}
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ftn.domij.securitydsl.SecurityDsl.Model");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cUserParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cOtherModelParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cRoleParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Model returns Model:
		//    User | OtherModel | Role;
		@Override public ParserRule getRule() { return rule; }
		
		//User | OtherModel | Role
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//User
		public RuleCall getUserParserRuleCall_0() { return cUserParserRuleCall_0; }
		
		//OtherModel
		public RuleCall getOtherModelParserRuleCall_1() { return cOtherModelParserRuleCall_1; }
		
		//Role
		public RuleCall getRoleParserRuleCall_2() { return cRoleParserRuleCall_2; }
	}
	public class ControllerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ftn.domij.securitydsl.SecurityDsl.Controller");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cAuthenticationParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cOtherControllerParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Controller returns Controller:
		//    Authentication | OtherController;
		@Override public ParserRule getRule() { return rule; }
		
		//Authentication | OtherController
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Authentication
		public RuleCall getAuthenticationParserRuleCall_0() { return cAuthenticationParserRuleCall_0; }
		
		//OtherController
		public RuleCall getOtherControllerParserRuleCall_1() { return cOtherControllerParserRuleCall_1; }
	}
	public class SecurityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ftn.domij.securitydsl.SecurityDsl.Security");
		private final RuleCall cJwtSecurityParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Security returns Security:
		//    JwtSecurity;
		@Override public ParserRule getRule() { return rule; }
		
		//JwtSecurity
		public RuleCall getJwtSecurityParserRuleCall() { return cJwtSecurityParserRuleCall; }
	}
	public class ClaimElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ftn.domij.securitydsl.SecurityDsl.Claim");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cPublicParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cPrivateParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Claim returns Claim:
		//    Public | Private;
		@Override public ParserRule getRule() { return rule; }
		
		//Public | Private
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Public
		public RuleCall getPublicParserRuleCall_0() { return cPublicParserRuleCall_0; }
		
		//Private
		public RuleCall getPrivateParserRuleCall_1() { return cPrivateParserRuleCall_1; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ftn.domij.securitydsl.SecurityDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class DatabaseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ftn.domij.securitydsl.SecurityDsl.Database");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVendorNameKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cVendorNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cVendorNameEDatabaseTypeEnumRuleCall_1_0 = (RuleCall)cVendorNameAssignment_1.eContents().get(0);
		private final Keyword cUrlKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cUrlAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cUrlEStringParserRuleCall_3_0 = (RuleCall)cUrlAssignment_3.eContents().get(0);
		private final Keyword cUsernameKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cUsernameAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cUsernameEStringParserRuleCall_5_0 = (RuleCall)cUsernameAssignment_5.eContents().get(0);
		private final Keyword cPasswordKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cPasswordAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cPasswordEStringParserRuleCall_7_0 = (RuleCall)cPasswordAssignment_7.eContents().get(0);
		
		//Database returns Database:
		//     'vendorName:'  vendorName=EDatabaseType
		//     'url:' url=EString
		//     'username:' username=EString
		//     'password:' password=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//'vendorName:'  vendorName=EDatabaseType
		//'url:' url=EString
		//'username:' username=EString
		//'password:' password=EString
		public Group getGroup() { return cGroup; }
		
		//'vendorName:'
		public Keyword getVendorNameKeyword_0() { return cVendorNameKeyword_0; }
		
		//vendorName=EDatabaseType
		public Assignment getVendorNameAssignment_1() { return cVendorNameAssignment_1; }
		
		//EDatabaseType
		public RuleCall getVendorNameEDatabaseTypeEnumRuleCall_1_0() { return cVendorNameEDatabaseTypeEnumRuleCall_1_0; }
		
		//'url:'
		public Keyword getUrlKeyword_2() { return cUrlKeyword_2; }
		
		//url=EString
		public Assignment getUrlAssignment_3() { return cUrlAssignment_3; }
		
		//EString
		public RuleCall getUrlEStringParserRuleCall_3_0() { return cUrlEStringParserRuleCall_3_0; }
		
		//'username:'
		public Keyword getUsernameKeyword_4() { return cUsernameKeyword_4; }
		
		//username=EString
		public Assignment getUsernameAssignment_5() { return cUsernameAssignment_5; }
		
		//EString
		public RuleCall getUsernameEStringParserRuleCall_5_0() { return cUsernameEStringParserRuleCall_5_0; }
		
		//'password:'
		public Keyword getPasswordKeyword_6() { return cPasswordKeyword_6; }
		
		//password=EString
		public Assignment getPasswordAssignment_7() { return cPasswordAssignment_7; }
		
		//EString
		public RuleCall getPasswordEStringParserRuleCall_7_0() { return cPasswordEStringParserRuleCall_7_0; }
	}
	public class AttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ftn.domij.securitydsl.SecurityDsl.Attribute");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cNameKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cTypeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTypeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTypeETypeEnumRuleCall_4_0 = (RuleCall)cTypeAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Attribute returns Attribute:
		//    '{'
		//    'name:' name=EString
		//    'type:' type=EType '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'{'
		//'name:' name=EString
		//'type:' type=EType '}'
		public Group getGroup() { return cGroup; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }
		
		//'name:'
		public Keyword getNameKeyword_1() { return cNameKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'type:'
		public Keyword getTypeKeyword_3() { return cTypeKeyword_3; }
		
		//type=EType
		public Assignment getTypeAssignment_4() { return cTypeAssignment_4; }
		
		//EType
		public RuleCall getTypeETypeEnumRuleCall_4_0() { return cTypeETypeEnumRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class UserElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ftn.domij.securitydsl.SecurityDsl.User");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIdentifierKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cNameKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cIdentifierNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cIdentifierNameEStringParserRuleCall_2_0 = (RuleCall)cIdentifierNameAssignment_2.eContents().get(0);
		private final Keyword cTypeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cIdentifierTypeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cIdentifierTypeETypeEnumRuleCall_4_0 = (RuleCall)cIdentifierTypeAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cOtherFieldsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cModel_attributesAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cModel_attributesAttributeParserRuleCall_5_2_0 = (RuleCall)cModel_attributesAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cModel_attributesAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cModel_attributesAttributeParserRuleCall_5_3_1_0 = (RuleCall)cModel_attributesAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		
		//User returns User:
		//    'identifier:'
		//        'name:' identifierName=EString
		//        'type:' identifierType=EType
		//    ('other-fields:' '[' model_attributes+=Attribute ( "," model_attributes+=Attribute)* ']' )?
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//'identifier:'
		//    'name:' identifierName=EString
		//    'type:' identifierType=EType
		//('other-fields:' '[' model_attributes+=Attribute ( "," model_attributes+=Attribute)* ']' )?
		public Group getGroup() { return cGroup; }
		
		//'identifier:'
		public Keyword getIdentifierKeyword_0() { return cIdentifierKeyword_0; }
		
		//'name:'
		public Keyword getNameKeyword_1() { return cNameKeyword_1; }
		
		//identifierName=EString
		public Assignment getIdentifierNameAssignment_2() { return cIdentifierNameAssignment_2; }
		
		//EString
		public RuleCall getIdentifierNameEStringParserRuleCall_2_0() { return cIdentifierNameEStringParserRuleCall_2_0; }
		
		//'type:'
		public Keyword getTypeKeyword_3() { return cTypeKeyword_3; }
		
		//identifierType=EType
		public Assignment getIdentifierTypeAssignment_4() { return cIdentifierTypeAssignment_4; }
		
		//EType
		public RuleCall getIdentifierTypeETypeEnumRuleCall_4_0() { return cIdentifierTypeETypeEnumRuleCall_4_0; }
		
		//('other-fields:' '[' model_attributes+=Attribute ( "," model_attributes+=Attribute)* ']' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'other-fields:'
		public Keyword getOtherFieldsKeyword_5_0() { return cOtherFieldsKeyword_5_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_5_1() { return cLeftSquareBracketKeyword_5_1; }
		
		//model_attributes+=Attribute
		public Assignment getModel_attributesAssignment_5_2() { return cModel_attributesAssignment_5_2; }
		
		//Attribute
		public RuleCall getModel_attributesAttributeParserRuleCall_5_2_0() { return cModel_attributesAttributeParserRuleCall_5_2_0; }
		
		//( "," model_attributes+=Attribute)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//model_attributes+=Attribute
		public Assignment getModel_attributesAssignment_5_3_1() { return cModel_attributesAssignment_5_3_1; }
		
		//Attribute
		public RuleCall getModel_attributesAttributeParserRuleCall_5_3_1_0() { return cModel_attributesAttributeParserRuleCall_5_3_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_5_4() { return cRightSquareBracketKeyword_5_4; }
	}
	public class OtherModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ftn.domij.securitydsl.SecurityDsl.OtherModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cNameKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cIdentifierKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cNameKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cIdentifierNameAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cIdentifierNameEStringParserRuleCall_5_0 = (RuleCall)cIdentifierNameAssignment_5.eContents().get(0);
		private final Keyword cTypeKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cIdentifierTypeAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cIdentifierTypeETypeEnumRuleCall_7_0 = (RuleCall)cIdentifierTypeAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cOtherFieldsKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cModel_attributesAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cModel_attributesAttributeParserRuleCall_8_2_0 = (RuleCall)cModel_attributesAssignment_8_2.eContents().get(0);
		private final Group cGroup_8_3 = (Group)cGroup_8.eContents().get(3);
		private final Keyword cCommaKeyword_8_3_0 = (Keyword)cGroup_8_3.eContents().get(0);
		private final Assignment cModel_attributesAssignment_8_3_1 = (Assignment)cGroup_8_3.eContents().get(1);
		private final RuleCall cModel_attributesAttributeParserRuleCall_8_3_1_0 = (RuleCall)cModel_attributesAssignment_8_3_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_8_4 = (Keyword)cGroup_8.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//OtherModel returns OtherModel:
		//    '{'
		//    'name:' name = EString
		//    'identifier:'
		//        'name:' identifierName=EString
		//        'type:' identifierType=EType
		//    ('other-fields:' '[' model_attributes+=Attribute ( "," model_attributes+=Attribute)* ']' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'{'
		//'name:' name = EString
		//'identifier:'
		//    'name:' identifierName=EString
		//    'type:' identifierType=EType
		//('other-fields:' '[' model_attributes+=Attribute ( "," model_attributes+=Attribute)* ']' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }
		
		//'name:'
		public Keyword getNameKeyword_1() { return cNameKeyword_1; }
		
		//name = EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'identifier:'
		public Keyword getIdentifierKeyword_3() { return cIdentifierKeyword_3; }
		
		//'name:'
		public Keyword getNameKeyword_4() { return cNameKeyword_4; }
		
		//identifierName=EString
		public Assignment getIdentifierNameAssignment_5() { return cIdentifierNameAssignment_5; }
		
		//EString
		public RuleCall getIdentifierNameEStringParserRuleCall_5_0() { return cIdentifierNameEStringParserRuleCall_5_0; }
		
		//'type:'
		public Keyword getTypeKeyword_6() { return cTypeKeyword_6; }
		
		//identifierType=EType
		public Assignment getIdentifierTypeAssignment_7() { return cIdentifierTypeAssignment_7; }
		
		//EType
		public RuleCall getIdentifierTypeETypeEnumRuleCall_7_0() { return cIdentifierTypeETypeEnumRuleCall_7_0; }
		
		//('other-fields:' '[' model_attributes+=Attribute ( "," model_attributes+=Attribute)* ']' )?
		public Group getGroup_8() { return cGroup_8; }
		
		//'other-fields:'
		public Keyword getOtherFieldsKeyword_8_0() { return cOtherFieldsKeyword_8_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_8_1() { return cLeftSquareBracketKeyword_8_1; }
		
		//model_attributes+=Attribute
		public Assignment getModel_attributesAssignment_8_2() { return cModel_attributesAssignment_8_2; }
		
		//Attribute
		public RuleCall getModel_attributesAttributeParserRuleCall_8_2_0() { return cModel_attributesAttributeParserRuleCall_8_2_0; }
		
		//( "," model_attributes+=Attribute)*
		public Group getGroup_8_3() { return cGroup_8_3; }
		
		//","
		public Keyword getCommaKeyword_8_3_0() { return cCommaKeyword_8_3_0; }
		
		//model_attributes+=Attribute
		public Assignment getModel_attributesAssignment_8_3_1() { return cModel_attributesAssignment_8_3_1; }
		
		//Attribute
		public RuleCall getModel_attributesAttributeParserRuleCall_8_3_1_0() { return cModel_attributesAttributeParserRuleCall_8_3_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_8_4() { return cRightSquareBracketKeyword_8_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class RoleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ftn.domij.securitydsl.SecurityDsl.Role");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIdentifierKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cNameKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cIdentifierNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cIdentifierNameEStringParserRuleCall_2_0 = (RuleCall)cIdentifierNameAssignment_2.eContents().get(0);
		private final Keyword cTypeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cIdentifierTypeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cIdentifierTypeETypeEnumRuleCall_4_0 = (RuleCall)cIdentifierTypeAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cOtherFieldsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cModel_attributesAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cModel_attributesAttributeParserRuleCall_5_2_0 = (RuleCall)cModel_attributesAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cModel_attributesAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cModel_attributesAttributeParserRuleCall_5_3_1_0 = (RuleCall)cModel_attributesAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		
		//Role returns Role:
		//    'identifier:'
		//        'name:' identifierName=EString
		//        'type:' identifierType=EType
		//    ('other-fields:' '[' model_attributes+=Attribute ( "," model_attributes+=Attribute)* ']' )?
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//'identifier:'
		//    'name:' identifierName=EString
		//    'type:' identifierType=EType
		//('other-fields:' '[' model_attributes+=Attribute ( "," model_attributes+=Attribute)* ']' )?
		public Group getGroup() { return cGroup; }
		
		//'identifier:'
		public Keyword getIdentifierKeyword_0() { return cIdentifierKeyword_0; }
		
		//'name:'
		public Keyword getNameKeyword_1() { return cNameKeyword_1; }
		
		//identifierName=EString
		public Assignment getIdentifierNameAssignment_2() { return cIdentifierNameAssignment_2; }
		
		//EString
		public RuleCall getIdentifierNameEStringParserRuleCall_2_0() { return cIdentifierNameEStringParserRuleCall_2_0; }
		
		//'type:'
		public Keyword getTypeKeyword_3() { return cTypeKeyword_3; }
		
		//identifierType=EType
		public Assignment getIdentifierTypeAssignment_4() { return cIdentifierTypeAssignment_4; }
		
		//EType
		public RuleCall getIdentifierTypeETypeEnumRuleCall_4_0() { return cIdentifierTypeETypeEnumRuleCall_4_0; }
		
		//('other-fields:' '[' model_attributes+=Attribute ( "," model_attributes+=Attribute)* ']' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'other-fields:'
		public Keyword getOtherFieldsKeyword_5_0() { return cOtherFieldsKeyword_5_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_5_1() { return cLeftSquareBracketKeyword_5_1; }
		
		//model_attributes+=Attribute
		public Assignment getModel_attributesAssignment_5_2() { return cModel_attributesAssignment_5_2; }
		
		//Attribute
		public RuleCall getModel_attributesAttributeParserRuleCall_5_2_0() { return cModel_attributesAttributeParserRuleCall_5_2_0; }
		
		//( "," model_attributes+=Attribute)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//model_attributes+=Attribute
		public Assignment getModel_attributesAssignment_5_3_1() { return cModel_attributesAssignment_5_3_1; }
		
		//Attribute
		public RuleCall getModel_attributesAttributeParserRuleCall_5_3_1_0() { return cModel_attributesAttributeParserRuleCall_5_3_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_5_4() { return cRightSquareBracketKeyword_5_4; }
	}
	public class EndpointElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ftn.domij.securitydsl.SecurityDsl.Endpoint");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cUrlKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cUrlAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cUrlEStringParserRuleCall_2_0 = (RuleCall)cUrlAssignment_2.eContents().get(0);
		private final Keyword cMethodNameKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cFunction_nameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cFunction_nameEStringParserRuleCall_4_0 = (RuleCall)cFunction_nameAssignment_4.eContents().get(0);
		private final Keyword cMethodKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cMethodAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cMethodEEndpointMethodEnumRuleCall_6_0 = (RuleCall)cMethodAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Endpoint returns Endpoint:
		//    '{'
		//        'url:' url=EString
		//        'method-name:' function_name=EString
		//        'method:' method=EEndpointMethod
		//        //('roles_authority' '(' roles_authority+=[Role|EString] ( "," roles_authority+=[Role|EString])* ')' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'{'
		//    'url:' url=EString
		//    'method-name:' function_name=EString
		//    'method:' method=EEndpointMethod
		//    //('roles_authority' '(' roles_authority+=[Role|EString] ( "," roles_authority+=[Role|EString])* ')' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }
		
		//'url:'
		public Keyword getUrlKeyword_1() { return cUrlKeyword_1; }
		
		//url=EString
		public Assignment getUrlAssignment_2() { return cUrlAssignment_2; }
		
		//EString
		public RuleCall getUrlEStringParserRuleCall_2_0() { return cUrlEStringParserRuleCall_2_0; }
		
		//'method-name:'
		public Keyword getMethodNameKeyword_3() { return cMethodNameKeyword_3; }
		
		//function_name=EString
		public Assignment getFunction_nameAssignment_4() { return cFunction_nameAssignment_4; }
		
		//EString
		public RuleCall getFunction_nameEStringParserRuleCall_4_0() { return cFunction_nameEStringParserRuleCall_4_0; }
		
		//'method:'
		public Keyword getMethodKeyword_5() { return cMethodKeyword_5; }
		
		//method=EEndpointMethod
		public Assignment getMethodAssignment_6() { return cMethodAssignment_6; }
		
		//EEndpointMethod
		public RuleCall getMethodEEndpointMethodEnumRuleCall_6_0() { return cMethodEEndpointMethodEnumRuleCall_6_0; }
		
		//    //('roles_authority' '(' roles_authority+=[Role|EString] ( "," roles_authority+=[Role|EString])* ')' )?
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class AuthEndpointElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ftn.domij.securitydsl.SecurityDsl.AuthEndpoint");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUrlKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cUrlAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cUrlEStringParserRuleCall_1_0 = (RuleCall)cUrlAssignment_1.eContents().get(0);
		private final Keyword cMethodNameKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cFunction_nameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cFunction_nameEStringParserRuleCall_3_0 = (RuleCall)cFunction_nameAssignment_3.eContents().get(0);
		private final Keyword cMethodKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cMethodAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cMethodEEndpointMethodEnumRuleCall_5_0 = (RuleCall)cMethodAssignment_5.eContents().get(0);
		
		//AuthEndpoint returns Endpoint:
		//        'url:' url=EString
		//        'method-name:' function_name=EString
		//        'method:' method=EEndpointMethod //proveriti kako da ne stavim tu nego da zapucam
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'url:' url=EString
		//'method-name:' function_name=EString
		//'method:' method=EEndpointMethod
		public Group getGroup() { return cGroup; }
		
		//'url:'
		public Keyword getUrlKeyword_0() { return cUrlKeyword_0; }
		
		//url=EString
		public Assignment getUrlAssignment_1() { return cUrlAssignment_1; }
		
		//EString
		public RuleCall getUrlEStringParserRuleCall_1_0() { return cUrlEStringParserRuleCall_1_0; }
		
		//'method-name:'
		public Keyword getMethodNameKeyword_2() { return cMethodNameKeyword_2; }
		
		//function_name=EString
		public Assignment getFunction_nameAssignment_3() { return cFunction_nameAssignment_3; }
		
		//EString
		public RuleCall getFunction_nameEStringParserRuleCall_3_0() { return cFunction_nameEStringParserRuleCall_3_0; }
		
		//'method:'
		public Keyword getMethodKeyword_4() { return cMethodKeyword_4; }
		
		//method=EEndpointMethod
		public Assignment getMethodAssignment_5() { return cMethodAssignment_5; }
		
		//EEndpointMethod
		public RuleCall getMethodEEndpointMethodEnumRuleCall_5_0() { return cMethodEEndpointMethodEnumRuleCall_5_0; }
	}
	public class AuthenticationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ftn.domij.securitydsl.SecurityDsl.Authentication");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNameKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cPathKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPathAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPathEStringParserRuleCall_3_0 = (RuleCall)cPathAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cSignupUrlKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cSignup_endpointAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cSignup_endpointAuthEndpointParserRuleCall_4_1_0 = (RuleCall)cSignup_endpointAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLoginUrlKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cLogin_endpointAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cLogin_endpointAuthEndpointParserRuleCall_5_1_0 = (RuleCall)cLogin_endpointAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cLogoutUrlKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cLogout_endpointAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cLogout_endpointAuthEndpointParserRuleCall_6_1_0 = (RuleCall)cLogout_endpointAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cEndpointsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cController_endpointsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cController_endpointsEndpointParserRuleCall_7_2_0 = (RuleCall)cController_endpointsAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cController_endpointsAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cController_endpointsEndpointParserRuleCall_7_3_1_0 = (RuleCall)cController_endpointsAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		
		//Authentication returns Authentication:
		//    'name:' name=EString
		//    'path:' path=EString
		//    ('signup-url:' signup_endpoint=AuthEndpoint)?
		//    ('login-url:' login_endpoint=AuthEndpoint)?
		//    ('logout-url:' logout_endpoint=AuthEndpoint)?
		//    ('endpoints:' '[' controller_endpoints+=Endpoint ( "," controller_endpoints+=Endpoint)* ']' )?
		//        ;
		@Override public ParserRule getRule() { return rule; }
		
		//'name:' name=EString
		//'path:' path=EString
		//('signup-url:' signup_endpoint=AuthEndpoint)?
		//('login-url:' login_endpoint=AuthEndpoint)?
		//('logout-url:' logout_endpoint=AuthEndpoint)?
		//('endpoints:' '[' controller_endpoints+=Endpoint ( "," controller_endpoints+=Endpoint)* ']' )?
		public Group getGroup() { return cGroup; }
		
		//'name:'
		public Keyword getNameKeyword_0() { return cNameKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'path:'
		public Keyword getPathKeyword_2() { return cPathKeyword_2; }
		
		//path=EString
		public Assignment getPathAssignment_3() { return cPathAssignment_3; }
		
		//EString
		public RuleCall getPathEStringParserRuleCall_3_0() { return cPathEStringParserRuleCall_3_0; }
		
		//('signup-url:' signup_endpoint=AuthEndpoint)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'signup-url:'
		public Keyword getSignupUrlKeyword_4_0() { return cSignupUrlKeyword_4_0; }
		
		//signup_endpoint=AuthEndpoint
		public Assignment getSignup_endpointAssignment_4_1() { return cSignup_endpointAssignment_4_1; }
		
		//AuthEndpoint
		public RuleCall getSignup_endpointAuthEndpointParserRuleCall_4_1_0() { return cSignup_endpointAuthEndpointParserRuleCall_4_1_0; }
		
		//('login-url:' login_endpoint=AuthEndpoint)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'login-url:'
		public Keyword getLoginUrlKeyword_5_0() { return cLoginUrlKeyword_5_0; }
		
		//login_endpoint=AuthEndpoint
		public Assignment getLogin_endpointAssignment_5_1() { return cLogin_endpointAssignment_5_1; }
		
		//AuthEndpoint
		public RuleCall getLogin_endpointAuthEndpointParserRuleCall_5_1_0() { return cLogin_endpointAuthEndpointParserRuleCall_5_1_0; }
		
		//('logout-url:' logout_endpoint=AuthEndpoint)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'logout-url:'
		public Keyword getLogoutUrlKeyword_6_0() { return cLogoutUrlKeyword_6_0; }
		
		//logout_endpoint=AuthEndpoint
		public Assignment getLogout_endpointAssignment_6_1() { return cLogout_endpointAssignment_6_1; }
		
		//AuthEndpoint
		public RuleCall getLogout_endpointAuthEndpointParserRuleCall_6_1_0() { return cLogout_endpointAuthEndpointParserRuleCall_6_1_0; }
		
		//('endpoints:' '[' controller_endpoints+=Endpoint ( "," controller_endpoints+=Endpoint)* ']' )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'endpoints:'
		public Keyword getEndpointsKeyword_7_0() { return cEndpointsKeyword_7_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_7_1() { return cLeftSquareBracketKeyword_7_1; }
		
		//controller_endpoints+=Endpoint
		public Assignment getController_endpointsAssignment_7_2() { return cController_endpointsAssignment_7_2; }
		
		//Endpoint
		public RuleCall getController_endpointsEndpointParserRuleCall_7_2_0() { return cController_endpointsEndpointParserRuleCall_7_2_0; }
		
		//( "," controller_endpoints+=Endpoint)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//controller_endpoints+=Endpoint
		public Assignment getController_endpointsAssignment_7_3_1() { return cController_endpointsAssignment_7_3_1; }
		
		//Endpoint
		public RuleCall getController_endpointsEndpointParserRuleCall_7_3_1_0() { return cController_endpointsEndpointParserRuleCall_7_3_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_7_4() { return cRightSquareBracketKeyword_7_4; }
	}
	public class OtherControllerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ftn.domij.securitydsl.SecurityDsl.OtherController");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cNameKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cPathKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPathAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPathEStringParserRuleCall_4_0 = (RuleCall)cPathAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cEndpointsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cController_endpointsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cController_endpointsEndpointParserRuleCall_5_2_0 = (RuleCall)cController_endpointsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cController_endpointsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cController_endpointsEndpointParserRuleCall_5_3_1_0 = (RuleCall)cController_endpointsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//OtherController returns OtherController:
		//    '{''name:' name=EString
		//    'path:' path=EString
		//    ('endpoints:' '[' controller_endpoints+=Endpoint ( "," controller_endpoints+=Endpoint)* ']' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'{''name:' name=EString
		//'path:' path=EString
		//('endpoints:' '[' controller_endpoints+=Endpoint ( "," controller_endpoints+=Endpoint)* ']' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }
		
		//'name:'
		public Keyword getNameKeyword_1() { return cNameKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'path:'
		public Keyword getPathKeyword_3() { return cPathKeyword_3; }
		
		//path=EString
		public Assignment getPathAssignment_4() { return cPathAssignment_4; }
		
		//EString
		public RuleCall getPathEStringParserRuleCall_4_0() { return cPathEStringParserRuleCall_4_0; }
		
		//('endpoints:' '[' controller_endpoints+=Endpoint ( "," controller_endpoints+=Endpoint)* ']' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'endpoints:'
		public Keyword getEndpointsKeyword_5_0() { return cEndpointsKeyword_5_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_5_1() { return cLeftSquareBracketKeyword_5_1; }
		
		//controller_endpoints+=Endpoint
		public Assignment getController_endpointsAssignment_5_2() { return cController_endpointsAssignment_5_2; }
		
		//Endpoint
		public RuleCall getController_endpointsEndpointParserRuleCall_5_2_0() { return cController_endpointsEndpointParserRuleCall_5_2_0; }
		
		//( "," controller_endpoints+=Endpoint)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//controller_endpoints+=Endpoint
		public Assignment getController_endpointsAssignment_5_3_1() { return cController_endpointsAssignment_5_3_1; }
		
		//Endpoint
		public RuleCall getController_endpointsEndpointParserRuleCall_5_3_1_0() { return cController_endpointsEndpointParserRuleCall_5_3_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_5_4() { return cRightSquareBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class JwtSecurityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ftn.domij.securitydsl.SecurityDsl.JwtSecurity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMechanismKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cMechanismAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cMechanismESecurityMechanismEnumRuleCall_1_0 = (RuleCall)cMechanismAssignment_1.eContents().get(0);
		private final Keyword cJwtKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cHeaderKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cSignatureAlgorithmKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cSignatureAlgorithmAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cSignatureAlgorithmEStringParserRuleCall_5_0 = (RuleCall)cSignatureAlgorithmAssignment_5.eContents().get(0);
		private final Keyword cPayloadKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cIssuerKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cIssuerAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cIssuerEStringParserRuleCall_8_0 = (RuleCall)cIssuerAssignment_8.eContents().get(0);
		private final Keyword cExpirationTimeKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cExpirationTimeAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cExpirationTimeEIntParserRuleCall_10_0 = (RuleCall)cExpirationTimeAssignment_10.eContents().get(0);
		private final Keyword cAudienceKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cAudienceAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cAudienceEStringParserRuleCall_12_0 = (RuleCall)cAudienceAssignment_12.eContents().get(0);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cPublicClaimsKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_13_1 = (Keyword)cGroup_13.eContents().get(1);
		private final Assignment cSecurity_claimsAssignment_13_2 = (Assignment)cGroup_13.eContents().get(2);
		private final RuleCall cSecurity_claimsPublicParserRuleCall_13_2_0 = (RuleCall)cSecurity_claimsAssignment_13_2.eContents().get(0);
		private final Group cGroup_13_3 = (Group)cGroup_13.eContents().get(3);
		private final Keyword cCommaKeyword_13_3_0 = (Keyword)cGroup_13_3.eContents().get(0);
		private final Assignment cSecurity_claimsAssignment_13_3_1 = (Assignment)cGroup_13_3.eContents().get(1);
		private final RuleCall cSecurity_claimsPublicParserRuleCall_13_3_1_0 = (RuleCall)cSecurity_claimsAssignment_13_3_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_13_4 = (Keyword)cGroup_13.eContents().get(4);
		private final Group cGroup_14 = (Group)cGroup.eContents().get(14);
		private final Keyword cPrivateClaimsKeyword_14_0 = (Keyword)cGroup_14.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_14_1 = (Keyword)cGroup_14.eContents().get(1);
		private final Assignment cSecurity_claimsAssignment_14_2 = (Assignment)cGroup_14.eContents().get(2);
		private final RuleCall cSecurity_claimsPrivateParserRuleCall_14_2_0 = (RuleCall)cSecurity_claimsAssignment_14_2.eContents().get(0);
		private final Group cGroup_14_3 = (Group)cGroup_14.eContents().get(3);
		private final Keyword cCommaKeyword_14_3_0 = (Keyword)cGroup_14_3.eContents().get(0);
		private final Assignment cSecurity_claimsAssignment_14_3_1 = (Assignment)cGroup_14_3.eContents().get(1);
		private final RuleCall cSecurity_claimsPrivateParserRuleCall_14_3_1_0 = (RuleCall)cSecurity_claimsAssignment_14_3_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_14_4 = (Keyword)cGroup_14.eContents().get(4);
		private final Keyword cSignatureKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Keyword cSecretKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Assignment cSecretAssignment_17 = (Assignment)cGroup.eContents().get(17);
		private final RuleCall cSecretEStringParserRuleCall_17_0 = (RuleCall)cSecretAssignment_17.eContents().get(0);
		
		//JwtSecurity returns JwtSecurity:
		//    'mechanism:'  mechanism=ESecurityMechanism
		//    'jwt:'
		//        'header:'
		//        'signature-algorithm:' signatureAlgorithm=EString
		//        'payload:'
		//        'issuer:' issuer=EString
		//        'expiration-time:' expirationTime=EInt
		//        'audience:' audience=EString
		//        ('public-claims:' '['  (security_claims+=Public)? ( "," security_claims+=Public)* ']')?
		//        ('private-claims:' '['  (security_claims+=Private)? ( "," security_claims+=Private)* ']')?
		//        'signature:'
		//        'secret:' secret=EString
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//'mechanism:'  mechanism=ESecurityMechanism
		//'jwt:'
		//    'header:'
		//    'signature-algorithm:' signatureAlgorithm=EString
		//    'payload:'
		//    'issuer:' issuer=EString
		//    'expiration-time:' expirationTime=EInt
		//    'audience:' audience=EString
		//    ('public-claims:' '['  (security_claims+=Public)? ( "," security_claims+=Public)* ']')?
		//    ('private-claims:' '['  (security_claims+=Private)? ( "," security_claims+=Private)* ']')?
		//    'signature:'
		//    'secret:' secret=EString
		public Group getGroup() { return cGroup; }
		
		//'mechanism:'
		public Keyword getMechanismKeyword_0() { return cMechanismKeyword_0; }
		
		//mechanism=ESecurityMechanism
		public Assignment getMechanismAssignment_1() { return cMechanismAssignment_1; }
		
		//ESecurityMechanism
		public RuleCall getMechanismESecurityMechanismEnumRuleCall_1_0() { return cMechanismESecurityMechanismEnumRuleCall_1_0; }
		
		//'jwt:'
		public Keyword getJwtKeyword_2() { return cJwtKeyword_2; }
		
		//'header:'
		public Keyword getHeaderKeyword_3() { return cHeaderKeyword_3; }
		
		//'signature-algorithm:'
		public Keyword getSignatureAlgorithmKeyword_4() { return cSignatureAlgorithmKeyword_4; }
		
		//signatureAlgorithm=EString
		public Assignment getSignatureAlgorithmAssignment_5() { return cSignatureAlgorithmAssignment_5; }
		
		//EString
		public RuleCall getSignatureAlgorithmEStringParserRuleCall_5_0() { return cSignatureAlgorithmEStringParserRuleCall_5_0; }
		
		//'payload:'
		public Keyword getPayloadKeyword_6() { return cPayloadKeyword_6; }
		
		//'issuer:'
		public Keyword getIssuerKeyword_7() { return cIssuerKeyword_7; }
		
		//issuer=EString
		public Assignment getIssuerAssignment_8() { return cIssuerAssignment_8; }
		
		//EString
		public RuleCall getIssuerEStringParserRuleCall_8_0() { return cIssuerEStringParserRuleCall_8_0; }
		
		//'expiration-time:'
		public Keyword getExpirationTimeKeyword_9() { return cExpirationTimeKeyword_9; }
		
		//expirationTime=EInt
		public Assignment getExpirationTimeAssignment_10() { return cExpirationTimeAssignment_10; }
		
		//EInt
		public RuleCall getExpirationTimeEIntParserRuleCall_10_0() { return cExpirationTimeEIntParserRuleCall_10_0; }
		
		//'audience:'
		public Keyword getAudienceKeyword_11() { return cAudienceKeyword_11; }
		
		//audience=EString
		public Assignment getAudienceAssignment_12() { return cAudienceAssignment_12; }
		
		//EString
		public RuleCall getAudienceEStringParserRuleCall_12_0() { return cAudienceEStringParserRuleCall_12_0; }
		
		//('public-claims:' '['  (security_claims+=Public)? ( "," security_claims+=Public)* ']')?
		public Group getGroup_13() { return cGroup_13; }
		
		//'public-claims:'
		public Keyword getPublicClaimsKeyword_13_0() { return cPublicClaimsKeyword_13_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_13_1() { return cLeftSquareBracketKeyword_13_1; }
		
		//(security_claims+=Public)?
		public Assignment getSecurity_claimsAssignment_13_2() { return cSecurity_claimsAssignment_13_2; }
		
		//Public
		public RuleCall getSecurity_claimsPublicParserRuleCall_13_2_0() { return cSecurity_claimsPublicParserRuleCall_13_2_0; }
		
		//( "," security_claims+=Public)*
		public Group getGroup_13_3() { return cGroup_13_3; }
		
		//","
		public Keyword getCommaKeyword_13_3_0() { return cCommaKeyword_13_3_0; }
		
		//security_claims+=Public
		public Assignment getSecurity_claimsAssignment_13_3_1() { return cSecurity_claimsAssignment_13_3_1; }
		
		//Public
		public RuleCall getSecurity_claimsPublicParserRuleCall_13_3_1_0() { return cSecurity_claimsPublicParserRuleCall_13_3_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_13_4() { return cRightSquareBracketKeyword_13_4; }
		
		//('private-claims:' '['  (security_claims+=Private)? ( "," security_claims+=Private)* ']')?
		public Group getGroup_14() { return cGroup_14; }
		
		//'private-claims:'
		public Keyword getPrivateClaimsKeyword_14_0() { return cPrivateClaimsKeyword_14_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_14_1() { return cLeftSquareBracketKeyword_14_1; }
		
		//(security_claims+=Private)?
		public Assignment getSecurity_claimsAssignment_14_2() { return cSecurity_claimsAssignment_14_2; }
		
		//Private
		public RuleCall getSecurity_claimsPrivateParserRuleCall_14_2_0() { return cSecurity_claimsPrivateParserRuleCall_14_2_0; }
		
		//( "," security_claims+=Private)*
		public Group getGroup_14_3() { return cGroup_14_3; }
		
		//","
		public Keyword getCommaKeyword_14_3_0() { return cCommaKeyword_14_3_0; }
		
		//security_claims+=Private
		public Assignment getSecurity_claimsAssignment_14_3_1() { return cSecurity_claimsAssignment_14_3_1; }
		
		//Private
		public RuleCall getSecurity_claimsPrivateParserRuleCall_14_3_1_0() { return cSecurity_claimsPrivateParserRuleCall_14_3_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_14_4() { return cRightSquareBracketKeyword_14_4; }
		
		//'signature:'
		public Keyword getSignatureKeyword_15() { return cSignatureKeyword_15; }
		
		//'secret:'
		public Keyword getSecretKeyword_16() { return cSecretKeyword_16; }
		
		//secret=EString
		public Assignment getSecretAssignment_17() { return cSecretAssignment_17; }
		
		//EString
		public RuleCall getSecretEStringParserRuleCall_17_0() { return cSecretEStringParserRuleCall_17_0; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ftn.domij.securitydsl.SecurityDsl.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class PublicElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ftn.domij.securitydsl.SecurityDsl.Public");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPublicAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Public returns Public:
		//    {Public}
		//    name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{Public}
		//name=EString
		public Group getGroup() { return cGroup; }
		
		//{Public}
		public Action getPublicAction_0() { return cPublicAction_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
	}
	public class PrivateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ftn.domij.securitydsl.SecurityDsl.Private");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPrivateAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Private returns Private:
		//    {Private}
		//    name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{Private}
		//name=EString
		public Group getGroup() { return cGroup; }
		
		//{Private}
		public Action getPrivateAction_0() { return cPrivateAction_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
	}
	
	public class ETypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.ftn.domij.securitydsl.SecurityDsl.EType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cINTEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cINTINTKeyword_0_0 = (Keyword)cINTEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cSTRINGEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cSTRINGSTRINGKeyword_1_0 = (Keyword)cSTRINGEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cFLOATEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cFLOATFLOATKeyword_2_0 = (Keyword)cFLOATEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cLONGEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cLONGLONGKeyword_3_0 = (Keyword)cLONGEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cCHAREnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cCHARCHARKeyword_4_0 = (Keyword)cCHAREnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cBOOLEANEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cBOOLEANBOOLEANKeyword_5_0 = (Keyword)cBOOLEANEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cDOUBLEEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cDOUBLEDOUBLEKeyword_6_0 = (Keyword)cDOUBLEEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cBYTEEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cBYTEBYTEKeyword_7_0 = (Keyword)cBYTEEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cSHORTEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cSHORTSHORTKeyword_8_0 = (Keyword)cSHORTEnumLiteralDeclaration_8.eContents().get(0);
		
		//enum EType returns EType:
		//                INT = 'INT' | STRING = 'STRING' | FLOAT = 'FLOAT' | LONG = 'LONG' | CHAR = 'CHAR' | BOOLEAN = 'BOOLEAN' | DOUBLE = 'DOUBLE' | BYTE = 'BYTE' | SHORT = 'SHORT';
		public EnumRule getRule() { return rule; }
		
		//INT = 'INT' | STRING = 'STRING' | FLOAT = 'FLOAT' | LONG = 'LONG' | CHAR = 'CHAR' | BOOLEAN = 'BOOLEAN' | DOUBLE = 'DOUBLE' | BYTE = 'BYTE' | SHORT = 'SHORT'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//INT = 'INT'
		public EnumLiteralDeclaration getINTEnumLiteralDeclaration_0() { return cINTEnumLiteralDeclaration_0; }
		
		//'INT'
		public Keyword getINTINTKeyword_0_0() { return cINTINTKeyword_0_0; }
		
		//STRING = 'STRING'
		public EnumLiteralDeclaration getSTRINGEnumLiteralDeclaration_1() { return cSTRINGEnumLiteralDeclaration_1; }
		
		//'STRING'
		public Keyword getSTRINGSTRINGKeyword_1_0() { return cSTRINGSTRINGKeyword_1_0; }
		
		//FLOAT = 'FLOAT'
		public EnumLiteralDeclaration getFLOATEnumLiteralDeclaration_2() { return cFLOATEnumLiteralDeclaration_2; }
		
		//'FLOAT'
		public Keyword getFLOATFLOATKeyword_2_0() { return cFLOATFLOATKeyword_2_0; }
		
		//LONG = 'LONG'
		public EnumLiteralDeclaration getLONGEnumLiteralDeclaration_3() { return cLONGEnumLiteralDeclaration_3; }
		
		//'LONG'
		public Keyword getLONGLONGKeyword_3_0() { return cLONGLONGKeyword_3_0; }
		
		//CHAR = 'CHAR'
		public EnumLiteralDeclaration getCHAREnumLiteralDeclaration_4() { return cCHAREnumLiteralDeclaration_4; }
		
		//'CHAR'
		public Keyword getCHARCHARKeyword_4_0() { return cCHARCHARKeyword_4_0; }
		
		//BOOLEAN = 'BOOLEAN'
		public EnumLiteralDeclaration getBOOLEANEnumLiteralDeclaration_5() { return cBOOLEANEnumLiteralDeclaration_5; }
		
		//'BOOLEAN'
		public Keyword getBOOLEANBOOLEANKeyword_5_0() { return cBOOLEANBOOLEANKeyword_5_0; }
		
		//DOUBLE = 'DOUBLE'
		public EnumLiteralDeclaration getDOUBLEEnumLiteralDeclaration_6() { return cDOUBLEEnumLiteralDeclaration_6; }
		
		//'DOUBLE'
		public Keyword getDOUBLEDOUBLEKeyword_6_0() { return cDOUBLEDOUBLEKeyword_6_0; }
		
		//BYTE = 'BYTE'
		public EnumLiteralDeclaration getBYTEEnumLiteralDeclaration_7() { return cBYTEEnumLiteralDeclaration_7; }
		
		//'BYTE'
		public Keyword getBYTEBYTEKeyword_7_0() { return cBYTEBYTEKeyword_7_0; }
		
		//SHORT = 'SHORT'
		public EnumLiteralDeclaration getSHORTEnumLiteralDeclaration_8() { return cSHORTEnumLiteralDeclaration_8; }
		
		//'SHORT'
		public Keyword getSHORTSHORTKeyword_8_0() { return cSHORTSHORTKeyword_8_0; }
	}
	public class EEndpointMethodElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.ftn.domij.securitydsl.SecurityDsl.EEndpointMethod");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cGETEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cGETGETKeyword_0_0 = (Keyword)cGETEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cPUTEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cPUTPUTKeyword_1_0 = (Keyword)cPUTEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cPOSTEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cPOSTPOSTKeyword_2_0 = (Keyword)cPOSTEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cDELETEEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cDELETEDELETEKeyword_3_0 = (Keyword)cDELETEEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum EEndpointMethod returns EEndpointMethod:
		//                GET = 'GET' | PUT = 'PUT' | POST = 'POST' | DELETE = 'DELETE';
		public EnumRule getRule() { return rule; }
		
		//GET = 'GET' | PUT = 'PUT' | POST = 'POST' | DELETE = 'DELETE'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//GET = 'GET'
		public EnumLiteralDeclaration getGETEnumLiteralDeclaration_0() { return cGETEnumLiteralDeclaration_0; }
		
		//'GET'
		public Keyword getGETGETKeyword_0_0() { return cGETGETKeyword_0_0; }
		
		//PUT = 'PUT'
		public EnumLiteralDeclaration getPUTEnumLiteralDeclaration_1() { return cPUTEnumLiteralDeclaration_1; }
		
		//'PUT'
		public Keyword getPUTPUTKeyword_1_0() { return cPUTPUTKeyword_1_0; }
		
		//POST = 'POST'
		public EnumLiteralDeclaration getPOSTEnumLiteralDeclaration_2() { return cPOSTEnumLiteralDeclaration_2; }
		
		//'POST'
		public Keyword getPOSTPOSTKeyword_2_0() { return cPOSTPOSTKeyword_2_0; }
		
		//DELETE = 'DELETE'
		public EnumLiteralDeclaration getDELETEEnumLiteralDeclaration_3() { return cDELETEEnumLiteralDeclaration_3; }
		
		//'DELETE'
		public Keyword getDELETEDELETEKeyword_3_0() { return cDELETEDELETEKeyword_3_0; }
	}
	public class ESecurityMechanismElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.ftn.domij.securitydsl.SecurityDsl.ESecurityMechanism");
		private final EnumLiteralDeclaration cJWTEnumLiteralDeclaration = (EnumLiteralDeclaration)rule.eContents().get(1);
		private final Keyword cJWTJWTKeyword_0 = (Keyword)cJWTEnumLiteralDeclaration.eContents().get(0);
		
		//enum ESecurityMechanism returns ESecurityMechanism:
		//                JWT = 'JWT';
		public EnumRule getRule() { return rule; }
		
		//JWT = 'JWT'
		public EnumLiteralDeclaration getJWTEnumLiteralDeclaration() { return cJWTEnumLiteralDeclaration; }
		
		//'JWT'
		public Keyword getJWTJWTKeyword_0() { return cJWTJWTKeyword_0; }
	}
	public class EDatabaseTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.ftn.domij.securitydsl.SecurityDsl.EDatabaseType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cPOSTGRESEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cPOSTGRESPOSTGRESKeyword_0_0 = (Keyword)cPOSTGRESEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cORACLEEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cORACLEORACLEKeyword_1_0 = (Keyword)cORACLEEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cMYSQLEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cMYSQLMYSQLKeyword_2_0 = (Keyword)cMYSQLEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum EDatabaseType returns EDatabaseType:
		//                POSTGRES = 'POSTGRES' | ORACLE = 'ORACLE' | MYSQL = 'MYSQL';
		public EnumRule getRule() { return rule; }
		
		//POSTGRES = 'POSTGRES' | ORACLE = 'ORACLE' | MYSQL = 'MYSQL'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//POSTGRES = 'POSTGRES'
		public EnumLiteralDeclaration getPOSTGRESEnumLiteralDeclaration_0() { return cPOSTGRESEnumLiteralDeclaration_0; }
		
		//'POSTGRES'
		public Keyword getPOSTGRESPOSTGRESKeyword_0_0() { return cPOSTGRESPOSTGRESKeyword_0_0; }
		
		//ORACLE = 'ORACLE'
		public EnumLiteralDeclaration getORACLEEnumLiteralDeclaration_1() { return cORACLEEnumLiteralDeclaration_1; }
		
		//'ORACLE'
		public Keyword getORACLEORACLEKeyword_1_0() { return cORACLEORACLEKeyword_1_0; }
		
		//MYSQL = 'MYSQL'
		public EnumLiteralDeclaration getMYSQLEnumLiteralDeclaration_2() { return cMYSQLEnumLiteralDeclaration_2; }
		
		//'MYSQL'
		public Keyword getMYSQLMYSQLKeyword_2_0() { return cMYSQLMYSQLKeyword_2_0; }
	}
	
	private final ApplicationElements pApplication;
	private final ModelElements pModel;
	private final ControllerElements pController;
	private final SecurityElements pSecurity;
	private final ClaimElements pClaim;
	private final EStringElements pEString;
	private final DatabaseElements pDatabase;
	private final ETypeElements eEType;
	private final AttributeElements pAttribute;
	private final UserElements pUser;
	private final OtherModelElements pOtherModel;
	private final RoleElements pRole;
	private final EndpointElements pEndpoint;
	private final AuthEndpointElements pAuthEndpoint;
	private final AuthenticationElements pAuthentication;
	private final OtherControllerElements pOtherController;
	private final EEndpointMethodElements eEEndpointMethod;
	private final ESecurityMechanismElements eESecurityMechanism;
	private final JwtSecurityElements pJwtSecurity;
	private final EIntElements pEInt;
	private final PublicElements pPublic;
	private final PrivateElements pPrivate;
	private final EDatabaseTypeElements eEDatabaseType;
	private final TerminalRule tNL;
	private final TerminalRule tTAB;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public SecurityDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pApplication = new ApplicationElements();
		this.pModel = new ModelElements();
		this.pController = new ControllerElements();
		this.pSecurity = new SecurityElements();
		this.pClaim = new ClaimElements();
		this.pEString = new EStringElements();
		this.pDatabase = new DatabaseElements();
		this.eEType = new ETypeElements();
		this.pAttribute = new AttributeElements();
		this.pUser = new UserElements();
		this.pOtherModel = new OtherModelElements();
		this.pRole = new RoleElements();
		this.pEndpoint = new EndpointElements();
		this.pAuthEndpoint = new AuthEndpointElements();
		this.pAuthentication = new AuthenticationElements();
		this.pOtherController = new OtherControllerElements();
		this.eEEndpointMethod = new EEndpointMethodElements();
		this.eESecurityMechanism = new ESecurityMechanismElements();
		this.pJwtSecurity = new JwtSecurityElements();
		this.pEInt = new EIntElements();
		this.pPublic = new PublicElements();
		this.pPrivate = new PrivateElements();
		this.eEDatabaseType = new EDatabaseTypeElements();
		this.tNL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.ftn.domij.securitydsl.SecurityDsl.NL");
		this.tTAB = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.ftn.domij.securitydsl.SecurityDsl.TAB");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.ftn.domij.securitydsl.SecurityDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Application returns Application:
	//    {Application}
	//    'application:'
	//     'name:' name=EString
	//    ( 'description:' description=EString )?
	//    ('database:'  app_database=Database)?
	//    ('security:' app_security=Security)?
	//    ('model:'
	//        ('user:' app_models+=User)?
	//        ('role:' app_models+=Role)?
	//        ('other:' '[' app_models+=OtherModel ( "," app_models+=OtherModel )* ']')?
	//    )?
	//    ('controllers:'
	//        ('auth:' app_controllers+=Authentication)?
	//        ('other:' '[' app_controllers+=OtherController ( "," app_controllers+=OtherController )* ']')?
	//    )?;
	public ApplicationElements getApplicationAccess() {
		return pApplication;
	}
	
	public ParserRule getApplicationRule() {
		return getApplicationAccess().getRule();
	}
	
	//Model returns Model:
	//    User | OtherModel | Role;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Controller returns Controller:
	//    Authentication | OtherController;
	public ControllerElements getControllerAccess() {
		return pController;
	}
	
	public ParserRule getControllerRule() {
		return getControllerAccess().getRule();
	}
	
	//Security returns Security:
	//    JwtSecurity;
	public SecurityElements getSecurityAccess() {
		return pSecurity;
	}
	
	public ParserRule getSecurityRule() {
		return getSecurityAccess().getRule();
	}
	
	//Claim returns Claim:
	//    Public | Private;
	public ClaimElements getClaimAccess() {
		return pClaim;
	}
	
	public ParserRule getClaimRule() {
		return getClaimAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Database returns Database:
	//     'vendorName:'  vendorName=EDatabaseType
	//     'url:' url=EString
	//     'username:' username=EString
	//     'password:' password=EString;
	public DatabaseElements getDatabaseAccess() {
		return pDatabase;
	}
	
	public ParserRule getDatabaseRule() {
		return getDatabaseAccess().getRule();
	}
	
	//enum EType returns EType:
	//                INT = 'INT' | STRING = 'STRING' | FLOAT = 'FLOAT' | LONG = 'LONG' | CHAR = 'CHAR' | BOOLEAN = 'BOOLEAN' | DOUBLE = 'DOUBLE' | BYTE = 'BYTE' | SHORT = 'SHORT';
	public ETypeElements getETypeAccess() {
		return eEType;
	}
	
	public EnumRule getETypeRule() {
		return getETypeAccess().getRule();
	}
	
	//Attribute returns Attribute:
	//    '{'
	//    'name:' name=EString
	//    'type:' type=EType '}';
	public AttributeElements getAttributeAccess() {
		return pAttribute;
	}
	
	public ParserRule getAttributeRule() {
		return getAttributeAccess().getRule();
	}
	
	//User returns User:
	//    'identifier:'
	//        'name:' identifierName=EString
	//        'type:' identifierType=EType
	//    ('other-fields:' '[' model_attributes+=Attribute ( "," model_attributes+=Attribute)* ']' )?
	//    ;
	public UserElements getUserAccess() {
		return pUser;
	}
	
	public ParserRule getUserRule() {
		return getUserAccess().getRule();
	}
	
	//OtherModel returns OtherModel:
	//    '{'
	//    'name:' name = EString
	//    'identifier:'
	//        'name:' identifierName=EString
	//        'type:' identifierType=EType
	//    ('other-fields:' '[' model_attributes+=Attribute ( "," model_attributes+=Attribute)* ']' )?
	//    '}';
	public OtherModelElements getOtherModelAccess() {
		return pOtherModel;
	}
	
	public ParserRule getOtherModelRule() {
		return getOtherModelAccess().getRule();
	}
	
	//Role returns Role:
	//    'identifier:'
	//        'name:' identifierName=EString
	//        'type:' identifierType=EType
	//    ('other-fields:' '[' model_attributes+=Attribute ( "," model_attributes+=Attribute)* ']' )?
	//    ;
	public RoleElements getRoleAccess() {
		return pRole;
	}
	
	public ParserRule getRoleRule() {
		return getRoleAccess().getRule();
	}
	
	//Endpoint returns Endpoint:
	//    '{'
	//        'url:' url=EString
	//        'method-name:' function_name=EString
	//        'method:' method=EEndpointMethod
	//        //('roles_authority' '(' roles_authority+=[Role|EString] ( "," roles_authority+=[Role|EString])* ')' )?
	//    '}';
	public EndpointElements getEndpointAccess() {
		return pEndpoint;
	}
	
	public ParserRule getEndpointRule() {
		return getEndpointAccess().getRule();
	}
	
	//AuthEndpoint returns Endpoint:
	//        'url:' url=EString
	//        'method-name:' function_name=EString
	//        'method:' method=EEndpointMethod //proveriti kako da ne stavim tu nego da zapucam
	//;
	public AuthEndpointElements getAuthEndpointAccess() {
		return pAuthEndpoint;
	}
	
	public ParserRule getAuthEndpointRule() {
		return getAuthEndpointAccess().getRule();
	}
	
	//Authentication returns Authentication:
	//    'name:' name=EString
	//    'path:' path=EString
	//    ('signup-url:' signup_endpoint=AuthEndpoint)?
	//    ('login-url:' login_endpoint=AuthEndpoint)?
	//    ('logout-url:' logout_endpoint=AuthEndpoint)?
	//    ('endpoints:' '[' controller_endpoints+=Endpoint ( "," controller_endpoints+=Endpoint)* ']' )?
	//        ;
	public AuthenticationElements getAuthenticationAccess() {
		return pAuthentication;
	}
	
	public ParserRule getAuthenticationRule() {
		return getAuthenticationAccess().getRule();
	}
	
	//OtherController returns OtherController:
	//    '{''name:' name=EString
	//    'path:' path=EString
	//    ('endpoints:' '[' controller_endpoints+=Endpoint ( "," controller_endpoints+=Endpoint)* ']' )?
	//    '}';
	public OtherControllerElements getOtherControllerAccess() {
		return pOtherController;
	}
	
	public ParserRule getOtherControllerRule() {
		return getOtherControllerAccess().getRule();
	}
	
	//enum EEndpointMethod returns EEndpointMethod:
	//                GET = 'GET' | PUT = 'PUT' | POST = 'POST' | DELETE = 'DELETE';
	public EEndpointMethodElements getEEndpointMethodAccess() {
		return eEEndpointMethod;
	}
	
	public EnumRule getEEndpointMethodRule() {
		return getEEndpointMethodAccess().getRule();
	}
	
	//enum ESecurityMechanism returns ESecurityMechanism:
	//                JWT = 'JWT';
	public ESecurityMechanismElements getESecurityMechanismAccess() {
		return eESecurityMechanism;
	}
	
	public EnumRule getESecurityMechanismRule() {
		return getESecurityMechanismAccess().getRule();
	}
	
	//JwtSecurity returns JwtSecurity:
	//    'mechanism:'  mechanism=ESecurityMechanism
	//    'jwt:'
	//        'header:'
	//        'signature-algorithm:' signatureAlgorithm=EString
	//        'payload:'
	//        'issuer:' issuer=EString
	//        'expiration-time:' expirationTime=EInt
	//        'audience:' audience=EString
	//        ('public-claims:' '['  (security_claims+=Public)? ( "," security_claims+=Public)* ']')?
	//        ('private-claims:' '['  (security_claims+=Private)? ( "," security_claims+=Private)* ']')?
	//        'signature:'
	//        'secret:' secret=EString
	//    ;
	public JwtSecurityElements getJwtSecurityAccess() {
		return pJwtSecurity;
	}
	
	public ParserRule getJwtSecurityRule() {
		return getJwtSecurityAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//Public returns Public:
	//    {Public}
	//    name=EString;
	public PublicElements getPublicAccess() {
		return pPublic;
	}
	
	public ParserRule getPublicRule() {
		return getPublicAccess().getRule();
	}
	
	//Private returns Private:
	//    {Private}
	//    name=EString;
	public PrivateElements getPrivateAccess() {
		return pPrivate;
	}
	
	public ParserRule getPrivateRule() {
		return getPrivateAccess().getRule();
	}
	
	//enum EDatabaseType returns EDatabaseType:
	//                POSTGRES = 'POSTGRES' | ORACLE = 'ORACLE' | MYSQL = 'MYSQL';
	public EDatabaseTypeElements getEDatabaseTypeAccess() {
		return eEDatabaseType;
	}
	
	public EnumRule getEDatabaseTypeRule() {
		return getEDatabaseTypeAccess().getRule();
	}
	
	//terminal NL:
	//    '\r'? '\n';
	public TerminalRule getNLRule() {
		return tNL;
	}
	
	//terminal TAB:
	//    '\t';
	public TerminalRule getTABRule() {
		return tTAB;
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
