/*
 * generated by Xtext 2.27.0
 */
package org.xtext.securitydsl.ide;


/**
 * Use this class to register ide components.
 */
public class SecurityDslIdeModule extends AbstractSecurityDslIdeModule {
}
