/*
 * generated by Xtext 2.27.0
 */
package rs.ac.uns.ftn.securitydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import rs.ac.uns.ftn.securitydsl.ui.internal.SecuritydslActivator;

public class SecurityDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SecuritydslActivator.getInstance().getInjector("rs.ac.uns.ftn.securitydsl.SecurityDsl");
	}

}
