/*
 * generated by Xtext 2.27.0
 */
package rs.ac.uns.ftn.securitydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import rs.ac.uns.ftn.securitydsl.SecurityDslRuntimeModule;
import rs.ac.uns.ftn.securitydsl.SecurityDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SecurityDslIdeSetup extends SecurityDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SecurityDslRuntimeModule(), new SecurityDslIdeModule()));
	}
	
}
