/*
 * generated by Xtext 2.27.0
 */
package org.ftn.domij.securitydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.ftn.domij.securitydsl.ui.internal.SecuritydslActivator;

public class SecurityDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SecuritydslActivator.getInstance().getInjector("org.ftn.domij.securitydsl.SecurityDsl");
	}

}
