/*
 * generated by Xtext 2.27.0
 */
package org.ftn.domi.securitydsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.ftn.domi.securitydsl.ui.internal.SecuritydslActivator;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SecurityDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(SecuritydslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		SecuritydslActivator activator = SecuritydslActivator.getInstance();
		return activator != null ? activator.getInjector(SecuritydslActivator.ORG_FTN_DOMI_SECURITYDSL_SECURITYDSL) : null;
	}

}
