/*
 * generated by Xtext 2.27.0
 */
package rs.ac.uns.ftn.securitydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SecurityDslUiModule extends AbstractSecurityDslUiModule {

	public SecurityDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
