/*
 * generated by Xtext 2.27.0
 */
package rs.ac.uns.ftn.securitydsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSecurityDslScopeProvider extends DelegatingScopeProvider {
}
