package org.xtext.securitydsl.generator;

import com.google.common.base.Objects;
import com.google.common.collect.Iterators;
import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.xbase.lib.CollectionLiterals;
import org.eclipse.xtext.xbase.lib.StringExtensions;
import security_dsl.Application;
import security_dsl.Attribute;
import security_dsl.Authentication;
import security_dsl.Claim;
import security_dsl.Controller;
import security_dsl.EClaimType;
import security_dsl.EEndpointType;
import security_dsl.EType;
import security_dsl.Endpoint;
import security_dsl.JWT;
import security_dsl.RegisteredClaims;
import security_dsl.Security;
import security_dsl.User;

@SuppressWarnings("all")
public class SecurityDslJWTGenerator {
  public SecurityDslJWTGenerator(final Resource resource, final IFileSystemAccess2 fsa, final Application app, final String srcDestination) {
    User user = Iterators.<User>filter(resource.getAllContents(), User.class).next();
    String credentialNameUser = this.getCredential(user.getModel_attributes()).getName();
    fsa.generateFile((srcDestination + "/config/WebConfig.java"), this.generateWebConfig(app.getPackageName()));
    fsa.generateFile((srcDestination + "/config/WebSecurityConfig.java"), this.generateWebSecurityConfig(app.getPackageName(), this.getAuthController(app.getApp_controllers())));
    Security _app_security = app.getApp_security();
    fsa.generateFile((srcDestination + "/util/TokenUtils.java"), this.generateTokenUtils(app.getPackageName(), ((JWT) _app_security), credentialNameUser));
    fsa.generateFile((srcDestination + "/dto/UserTokenStateDTO.java"), this.generateUserTokenStateDTO(app.getPackageName()));
    fsa.generateFile((srcDestination + "/security/auth/RestAuthenticationEntryPoint.java"), this.generateRestAuthenticationEntryPoint(app.getPackageName()));
    fsa.generateFile((srcDestination + "/security/auth/TokenBasedAuthentication.java"), this.generateTokenBasedAuthentication(app.getPackageName()));
    fsa.generateFile((srcDestination + "/security/auth/TokenAuthenticationFilter.java"), this.generateTokenAuthenticationFilter(app.getPackageName()));
    fsa.generateFile((srcDestination + "/security/auth/TokenAuthenticationFilter.java"), this.generateTokenAuthenticationFilter(app.getPackageName()));
  }

  public String generateTokenAuthenticationFilter(final String packageName) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    _builder.append(packageName);
    _builder.append(".security.auth;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import java.io.IOException;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import javax.servlet.FilterChain;");
    _builder.newLine();
    _builder.append("import javax.servlet.ServletException;");
    _builder.newLine();
    _builder.append("import javax.servlet.http.HttpServletRequest;");
    _builder.newLine();
    _builder.append("import javax.servlet.http.HttpServletResponse;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import ");
    _builder.append(packageName);
    _builder.append(".util.TokenUtils;");
    _builder.newLineIfNotEmpty();
    _builder.append("import org.apache.commons.logging.Log;");
    _builder.newLine();
    _builder.append("import org.apache.commons.logging.LogFactory;");
    _builder.newLine();
    _builder.append("import org.springframework.security.core.context.SecurityContextHolder;");
    _builder.newLine();
    _builder.append("import org.springframework.security.core.userdetails.UserDetails;");
    _builder.newLine();
    _builder.append("import org.springframework.security.core.userdetails.UserDetailsService;");
    _builder.newLine();
    _builder.append("import org.springframework.web.filter.OncePerRequestFilter;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import io.jsonwebtoken.ExpiredJwtException;");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("public class TokenAuthenticationFilter extends OncePerRequestFilter {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private TokenUtils tokenUtils;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private UserDetailsService userDetailsService;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected final Log LOGGER = LogFactory.getLog(getClass());");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public TokenAuthenticationFilter(TokenUtils tokenHelper, UserDetailsService userDetailsService) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.tokenUtils = tokenHelper;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.userDetailsService = userDetailsService;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain chain)");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("throws IOException, ServletException {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("String credential;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("String authToken = tokenUtils.getToken(request);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("try {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("if (authToken != null) {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("                ");
    _builder.append("credential = tokenUtils.getCredentialFromToken(authToken);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("                ");
    _builder.append("if (credential != null) {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("UserDetails userDetails = userDetailsService.loadUserByUsername(credential);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("if (tokenUtils.validateToken(authToken, userDetails)) {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("TokenBasedAuthentication authentication = new TokenBasedAuthentication(userDetails);");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("authentication.setToken(authToken);");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("SecurityContextHolder.getContext().setAuthentication(authentication);");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("} catch (ExpiredJwtException ex) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("LOGGER.debug(\"Token expired!\");");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("chain.doFilter(request, response);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    String content = _builder.toString();
    return content;
  }

  public String generateTokenBasedAuthentication(final String packageName) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    _builder.append(packageName);
    _builder.append(".security.auth;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import org.springframework.security.authentication.AbstractAuthenticationToken;");
    _builder.newLine();
    _builder.append("import org.springframework.security.core.userdetails.UserDetails;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("public class TokenBasedAuthentication extends AbstractAuthenticationToken {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private static final long serialVersionUID = 1L;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private String token;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private final UserDetails principle;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public TokenBasedAuthentication(UserDetails principle) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("super(principle.getAuthorities());");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.principle = principle;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public String getToken() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return token;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void setToken(String token) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.token = token;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public boolean isAuthenticated() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return true;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public Object getCredentials() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return token;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public UserDetails getPrincipal() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return principle;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    String content = _builder.toString();
    return content;
  }

  public String generateRestAuthenticationEntryPoint(final String packageName) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    _builder.append(packageName);
    _builder.append(".security.auth;");
    _builder.newLineIfNotEmpty();
    _builder.append("import org.springframework.security.core.AuthenticationException;");
    _builder.newLine();
    _builder.append("import org.springframework.security.web.AuthenticationEntryPoint;");
    _builder.newLine();
    _builder.append("import org.springframework.stereotype.Component;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import javax.servlet.http.HttpServletRequest;");
    _builder.newLine();
    _builder.append("import javax.servlet.http.HttpServletResponse;");
    _builder.newLine();
    _builder.append("import java.io.IOException;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@Component");
    _builder.newLine();
    _builder.append("public class RestAuthenticationEntryPoint implements AuthenticationEntryPoint {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void commence(HttpServletRequest request,");
    _builder.newLine();
    _builder.append("                         ");
    _builder.append("HttpServletResponse response,");
    _builder.newLine();
    _builder.append("                         ");
    _builder.append("AuthenticationException authException) throws IOException {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("response.sendError(HttpServletResponse.SC_UNAUTHORIZED, authException.getMessage());");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    String content = _builder.toString();
    return content;
  }

  public String generateException(final String packageName) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    _builder.append(packageName);
    _builder.append(".exception;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("public class ResourceConflictException extends RuntimeException {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private static final long serialVersionUID = 1791564636123821405L;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private Long resourceId;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public ResourceConflictException(Long resourceId, String message) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("super(message);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.setResourceId(resourceId);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public Long getResourceId() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return resourceId;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void setResourceId(Long resourceId) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.resourceId = resourceId;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    String content = _builder.toString();
    return content;
  }

  public Authentication getAuthController(final List<Controller> controllers) {
    for (final Controller c : controllers) {
      if ((c instanceof Authentication)) {
        return ((Authentication)c);
      }
    }
    return null;
  }

  public String generateWebConfig(final String packageName) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    _builder.append(packageName);
    _builder.append(".config;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import org.springframework.context.annotation.Configuration;");
    _builder.newLine();
    _builder.append("import org.springframework.web.servlet.config.annotation.CorsRegistry;");
    _builder.newLine();
    _builder.append("import org.springframework.web.servlet.config.annotation.EnableWebMvc;");
    _builder.newLine();
    _builder.append("import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@Configuration");
    _builder.newLine();
    _builder.append("@EnableWebMvc");
    _builder.newLine();
    _builder.append("public class WebConfig implements WebMvcConfigurer {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void addCorsMappings(CorsRegistry registry) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("registry.addMapping(\"/**\")");
    _builder.newLine();
    _builder.append("                ");
    _builder.append(".allowedHeaders(\"*\")");
    _builder.newLine();
    _builder.append("                ");
    _builder.append(".allowedMethods(\"GET\", \"POST\", \"DELETE\", \"PUT\")");
    _builder.newLine();
    _builder.append("                ");
    _builder.append(".allowedOrigins(\"http://localhost:4200\");");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    String webConfig = _builder.toString();
    return webConfig;
  }

  public String generateWebSecurityConfig(final String packageName, final Authentication authController) {
    String loginEndpoint = "";
    EList<Endpoint> _controller_endpoints = authController.getController_endpoints();
    for (final Endpoint e : _controller_endpoints) {
      EEndpointType _type = e.getType();
      boolean _equals = Objects.equal(_type, EEndpointType.LOGIN);
      if (_equals) {
        String _path = authController.getPath();
        String _url = e.getUrl();
        String _plus = (_path + _url);
        loginEndpoint = _plus;
      }
    }
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    _builder.append(packageName);
    _builder.append(".config;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import ");
    _builder.append(packageName);
    _builder.append(".security.auth.RestAuthenticationEntryPoint;");
    _builder.newLineIfNotEmpty();
    _builder.append("import ");
    _builder.append(packageName);
    _builder.append(".security.auth.TokenAuthenticationFilter;");
    _builder.newLineIfNotEmpty();
    _builder.append("import ");
    _builder.append(packageName);
    _builder.append(".service.impl.UserServiceImpl;");
    _builder.newLineIfNotEmpty();
    _builder.append("import ");
    _builder.append(packageName);
    _builder.append(".util.TokenUtils;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import org.springframework.beans.factory.annotation.Autowired;");
    _builder.newLine();
    _builder.append("import org.springframework.context.annotation.Bean;");
    _builder.newLine();
    _builder.append("import org.springframework.context.annotation.Configuration;");
    _builder.newLine();
    _builder.append("import org.springframework.http.HttpMethod;");
    _builder.newLine();
    _builder.append("import org.springframework.security.authentication.AuthenticationManager;");
    _builder.newLine();
    _builder.append("import org.springframework.security.config.annotation.authentication.builders.AuthenticationManagerBuilder;");
    _builder.newLine();
    _builder.append("import org.springframework.security.config.annotation.method.configuration.EnableGlobalMethodSecurity;");
    _builder.newLine();
    _builder.append("import org.springframework.security.config.annotation.web.builders.HttpSecurity;");
    _builder.newLine();
    _builder.append("import org.springframework.security.config.annotation.web.builders.WebSecurity;");
    _builder.newLine();
    _builder.append("import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;");
    _builder.newLine();
    _builder.append("import org.springframework.security.config.http.SessionCreationPolicy;");
    _builder.newLine();
    _builder.append("import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;");
    _builder.newLine();
    _builder.append("import org.springframework.security.web.authentication.www.BasicAuthenticationFilter;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@Configuration");
    _builder.newLine();
    _builder.append("@EnableGlobalMethodSecurity(prePostEnabled = true)");
    _builder.newLine();
    _builder.append("public class WebSecurityConfig extends WebSecurityConfigurerAdapter {");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Autowired");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private UserServiceImpl userService;");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Autowired");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private RestAuthenticationEntryPoint restAuthenticationEntryPoint;");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Autowired");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private TokenUtils tokenUtils;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Bean");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public BCryptPasswordEncoder passwordEncoder() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return new BCryptPasswordEncoder();");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@Bean");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public AuthenticationManager authenticationManagerBean() throws Exception {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return super.authenticationManagerBean();");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void configure(AuthenticationManagerBuilder auth) throws Exception {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("auth");
    _builder.newLine();
    _builder.newLine();
    _builder.append("                ");
    _builder.append(".userDetailsService(userService)");
    _builder.newLine();
    _builder.append("                ");
    _builder.append(".passwordEncoder(passwordEncoder());");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected void configure(HttpSecurity http) throws Exception {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("http");
    _builder.newLine();
    _builder.newLine();
    _builder.append("                ");
    _builder.append(".sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS).and()");
    _builder.newLine();
    _builder.newLine();
    _builder.append("                ");
    _builder.append(".exceptionHandling().authenticationEntryPoint(restAuthenticationEntryPoint).and()");
    _builder.newLine();
    _builder.newLine();
    _builder.append("                ");
    _builder.append(".authorizeRequests().antMatchers(\"");
    String _path_1 = authController.getPath();
    _builder.append(_path_1, "                ");
    _builder.append("/**\").permitAll()");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("                ");
    _builder.append(".anyRequest().authenticated().and()");
    _builder.newLine();
    _builder.append("                ");
    _builder.append(".cors().and()");
    _builder.newLine();
    _builder.append("                ");
    _builder.append(".addFilterBefore(new TokenAuthenticationFilter(tokenUtils, userService), BasicAuthenticationFilter.class);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("http.csrf().disable();");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void configure(WebSecurity web) throws Exception {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("web.ignoring().antMatchers(HttpMethod.POST, \"");
    _builder.append(loginEndpoint, "        ");
    _builder.append("\");");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("web.ignoring().antMatchers(HttpMethod.GET, \"/\", \"/webjars/**\", \"/*.html\", \"favicon.ico\", \"/**/*.html\",");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("\"/**/*.css\", \"/**/*.js\");");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    String config = _builder.toString();
    return config;
  }

  public String generateTokenUtils(final String packageName, final JWT jwt, final String credentialNameUser) {
    RegisteredClaims regClaim = jwt.getRegisteredclaims();
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    _builder.append(packageName);
    _builder.append(".util;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import java.util.Date;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import javax.servlet.http.HttpServletRequest;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import org.springframework.beans.factory.annotation.Value;");
    _builder.newLine();
    _builder.append("import org.springframework.security.core.userdetails.UserDetails;");
    _builder.newLine();
    _builder.append("import org.springframework.stereotype.Component;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import io.jsonwebtoken.Claims;");
    _builder.newLine();
    _builder.append("import io.jsonwebtoken.ExpiredJwtException;");
    _builder.newLine();
    _builder.append("import io.jsonwebtoken.Jwts;");
    _builder.newLine();
    _builder.append("import io.jsonwebtoken.SignatureAlgorithm;");
    _builder.newLine();
    _builder.append("import ");
    _builder.append(packageName);
    _builder.append(".model.User;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("@Component");
    _builder.newLine();
    _builder.append("public class TokenUtils {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private String ISSUER = \"");
    String _issuer = regClaim.getIssuer();
    _builder.append(_issuer, "\t");
    _builder.append("\";");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public String SECRET = \"");
    String _secret = jwt.getSecret();
    _builder.append(_secret, "\t");
    _builder.append("\";");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private int EXPIRES_IN = ");
    int _expirationTime = regClaim.getExpirationTime();
    _builder.append(_expirationTime, "\t");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Value(\"Authorization\")");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private String AUTH_HEADER;");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private static final String AUDIENCE_WEB = \"");
    String _audience = regClaim.getAudience();
    _builder.append(_audience, "\t");
    _builder.append("\";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("// Algoritam za potpisivanje JWT");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private SignatureAlgorithm SIGNATURE_ALGORITHM = SignatureAlgorithm.");
    String _signatureAlgorithm = jwt.getSignatureAlgorithm();
    _builder.append(_signatureAlgorithm, "\t");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public String generateToken(String ");
    _builder.append(credentialNameUser, "\t");
    _builder.append(") {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("return Jwts.builder()");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append(".setIssuer(ISSUER)");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append(".setSubject(");
    String _name = this.findSubjectClaim(jwt.getJwt_claims()).getClaim_attribute().getName();
    _builder.append(_name, "\t\t\t\t");
    _builder.append(")");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t");
    _builder.append(".setAudience(generateAudience())");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append(".setIssuedAt(new Date())");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append(".setExpiration(generateExpirationDate())");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append(".signWith(SIGNATURE_ALGORITHM, SECRET).compact();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private String generateAudience() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return AUDIENCE_WEB;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private Date generateExpirationDate() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return new Date(new Date().getTime() + EXPIRES_IN);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public String getToken(HttpServletRequest request) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("String authHeader = getAuthHeaderFromHeader(request);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("if (authHeader != null && authHeader.startsWith(\"Bearer \")) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("return authHeader.substring(7); ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return null;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public String getCredentialFromToken(String token) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("String credential;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("final Claims claims = this.getAllClaimsFromToken(token);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("credential = claims.getSubject();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("} catch (ExpiredJwtException ex) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("throw ex;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("} catch (Exception e) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("credential = null;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return credential;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public Date getIssuedAtDateFromToken(String token) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("Date issueAt;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("final Claims claims = this.getAllClaimsFromToken(token);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("issueAt = claims.getIssuedAt();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("} catch (ExpiredJwtException ex) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("throw ex;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("} catch (Exception e) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("issueAt = null;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return issueAt;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public String getAudienceFromToken(String token) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("String audience;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("final Claims claims = this.getAllClaimsFromToken(token);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("audience = claims.getAudience();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("} catch (ExpiredJwtException ex) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("throw ex;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("} catch (Exception e) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("audience = null;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return audience;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public Date getExpirationDateFromToken(String token) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("Date expiration;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("final Claims claims = this.getAllClaimsFromToken(token);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("expiration = claims.getExpiration();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("} catch (ExpiredJwtException ex) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("throw ex;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("} catch (Exception e) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("expiration = null;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return expiration;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private Claims getAllClaimsFromToken(String token) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("Claims claims;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("claims = Jwts.parser()");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append(".setSigningKey(SECRET)");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append(".parseClaimsJws(token)");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append(".getBody();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("} catch (ExpiredJwtException ex) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("throw ex;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("} catch (Exception e) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("claims = null;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return claims;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public Boolean validateToken(String token, UserDetails userDetails) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("User user = (User) userDetails;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("final String credential = getCredentialFromToken(token);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("final Date created = getIssuedAtDateFromToken(token);");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return (credential != null ");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("&& credential.equals(userDetails.get");
    String _firstUpper = StringExtensions.toFirstUpper(credentialNameUser);
    _builder.append(_firstUpper, "\t\t\t");
    _builder.append("()) ");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("&& !isCreatedBeforeLastPasswordReset(created, user.getLastPasswordResetDate()));  ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private Boolean isCreatedBeforeLastPasswordReset(Date created, Date lastPasswordReset) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return (lastPasswordReset != null && created.before(lastPasswordReset));");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public int getExpiredIn() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return EXPIRES_IN;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public String getAuthHeaderFromHeader(HttpServletRequest request) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return request.getHeader(AUTH_HEADER);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    String utils = _builder.toString();
    return utils;
  }

  public Claim findSubjectClaim(final List<Claim> claims) {
    for (final Claim c : claims) {
      if ((Objects.equal(c.getType(), EClaimType.REGISTERED) && Objects.equal(c.getName().toLowerCase(), "subject"))) {
        return c;
      }
    }
    return null;
  }

  public Attribute getIdentifier(final List<Attribute> attributes) {
    for (final Attribute a : attributes) {
      boolean _isIdentifier = a.isIdentifier();
      if (_isIdentifier) {
        return a;
      }
    }
    return null;
  }

  public Attribute getCredential(final List<Attribute> attributes) {
    for (final Attribute a : attributes) {
      boolean _isCredential = a.isCredential();
      if (_isCredential) {
        return a;
      }
    }
    return null;
  }

  public Attribute getStringAttributeForRole(final List<Attribute> unsortedAttributes) {
    final ArrayList<Attribute> attributes = CollectionLiterals.<Attribute>newArrayList();
    for (final Attribute a : unsortedAttributes) {
      boolean _isIdentifier = a.isIdentifier();
      if (_isIdentifier) {
        attributes.add(0, a);
      } else {
        attributes.add(a);
      }
    }
    for (final Attribute a_1 : attributes) {
      EType _type = a_1.getType();
      boolean _equals = Objects.equal(_type, EType.STRING);
      if (_equals) {
        return a_1;
      }
    }
    return null;
  }

  public String generateUserTokenStateDTO(final String packageName) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    _builder.append(packageName);
    _builder.append(".dto;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("public class UserTokenStateDTO {");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private String accessToken;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private Long expiresIn;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public UserTokenStateDTO() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.accessToken = null;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.expiresIn = null;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public UserTokenStateDTO(String accessToken, long expiresIn) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.accessToken = accessToken;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.expiresIn = expiresIn;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public String getAccessToken() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return accessToken;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void setAccessToken(String accessToken) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.accessToken = accessToken;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public Long getExpiresIn() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return expiresIn;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void setExpiresIn(Long expiresIn) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.expiresIn = expiresIn;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    String content = _builder.toString();
    return content;
  }
}
