/*
 * generated by Xtext 2.27.0
 */
package org.xtext.securitydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class SecurityDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ApplicationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.securitydsl.SecurityDsl.Application");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cApplicationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cApplicationKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cArtifactKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cArtifactAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cArtifactEStringParserRuleCall_2_1_0 = (RuleCall)cArtifactAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNameKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_3_1_0 = (RuleCall)cNameAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cGroupKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cGroupAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cGroupEStringParserRuleCall_4_1_0 = (RuleCall)cGroupAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPackageNameKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cPackageNameAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cPackageNameEStringParserRuleCall_5_1_0 = (RuleCall)cPackageNameAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cDescriptionKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cDescriptionAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_6_1_0 = (RuleCall)cDescriptionAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cPortKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cPortAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cPortELongObjectParserRuleCall_7_1_0 = (RuleCall)cPortAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cHostnameKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cHostnameAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cHostnameEStringParserRuleCall_8_1_0 = (RuleCall)cHostnameAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cDatabaseKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cApp_databaseAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cApp_databaseDatabaseParserRuleCall_9_1_0 = (RuleCall)cApp_databaseAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cModelKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Group cGroup_10_1 = (Group)cGroup_10.eContents().get(1);
		private final Keyword cUserKeyword_10_1_0 = (Keyword)cGroup_10_1.eContents().get(0);
		private final Assignment cApp_modelsAssignment_10_1_1 = (Assignment)cGroup_10_1.eContents().get(1);
		private final RuleCall cApp_modelsUserParserRuleCall_10_1_1_0 = (RuleCall)cApp_modelsAssignment_10_1_1.eContents().get(0);
		private final Group cGroup_10_2 = (Group)cGroup_10.eContents().get(2);
		private final Keyword cRoleKeyword_10_2_0 = (Keyword)cGroup_10_2.eContents().get(0);
		private final Assignment cApp_modelsAssignment_10_2_1 = (Assignment)cGroup_10_2.eContents().get(1);
		private final RuleCall cApp_modelsRoleParserRuleCall_10_2_1_0 = (RuleCall)cApp_modelsAssignment_10_2_1.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cSecurityKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cApp_securityAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cApp_securitySecurityParserRuleCall_11_1_0 = (RuleCall)cApp_securityAssignment_11_1.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cControllerKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Group cGroup_12_1 = (Group)cGroup_12.eContents().get(1);
		private final Keyword cAuthKeyword_12_1_0 = (Keyword)cGroup_12_1.eContents().get(0);
		private final Assignment cApp_controllersAssignment_12_1_1 = (Assignment)cGroup_12_1.eContents().get(1);
		private final RuleCall cApp_controllersAuthenticationParserRuleCall_12_1_1_0 = (RuleCall)cApp_controllersAssignment_12_1_1.eContents().get(0);
		
		//Application returns Application:
		//    {Application}
		//    'application:'
		//    ('artifact:' artifact=EString)?
		//    ('name:' name=EString)?
		//    ('group:' group=EString)?
		//    ('packageName:' packageName=EString)?
		//    ('description:' description=EString)?
		//    ('port:' port=ELongObject)?
		//    ('hostname:' hostname=EString)?
		//    ('database:' app_database=Database)?
		//    ('model:'
		//        ('user:' app_models+=User)?
		//        ('role:' app_models+=Role)?
		//    )?
		//    ('security:' app_security=Security )?
		//    ('controller:'
		//        ('auth:' app_controllers+=Authentication)?
		//    )?
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{Application}
		//'application:'
		//('artifact:' artifact=EString)?
		//('name:' name=EString)?
		//('group:' group=EString)?
		//('packageName:' packageName=EString)?
		//('description:' description=EString)?
		//('port:' port=ELongObject)?
		//('hostname:' hostname=EString)?
		//('database:' app_database=Database)?
		//('model:'
		//    ('user:' app_models+=User)?
		//    ('role:' app_models+=Role)?
		//)?
		//('security:' app_security=Security )?
		//('controller:'
		//    ('auth:' app_controllers+=Authentication)?
		//)?
		public Group getGroup() { return cGroup; }
		
		//{Application}
		public Action getApplicationAction_0() { return cApplicationAction_0; }
		
		//'application:'
		public Keyword getApplicationKeyword_1() { return cApplicationKeyword_1; }
		
		//('artifact:' artifact=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'artifact:'
		public Keyword getArtifactKeyword_2_0() { return cArtifactKeyword_2_0; }
		
		//artifact=EString
		public Assignment getArtifactAssignment_2_1() { return cArtifactAssignment_2_1; }
		
		//EString
		public RuleCall getArtifactEStringParserRuleCall_2_1_0() { return cArtifactEStringParserRuleCall_2_1_0; }
		
		//('name:' name=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'name:'
		public Keyword getNameKeyword_3_0() { return cNameKeyword_3_0; }
		
		//name=EString
		public Assignment getNameAssignment_3_1() { return cNameAssignment_3_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_3_1_0() { return cNameEStringParserRuleCall_3_1_0; }
		
		//('group:' group=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'group:'
		public Keyword getGroupKeyword_4_0() { return cGroupKeyword_4_0; }
		
		//group=EString
		public Assignment getGroupAssignment_4_1() { return cGroupAssignment_4_1; }
		
		//EString
		public RuleCall getGroupEStringParserRuleCall_4_1_0() { return cGroupEStringParserRuleCall_4_1_0; }
		
		//('packageName:' packageName=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'packageName:'
		public Keyword getPackageNameKeyword_5_0() { return cPackageNameKeyword_5_0; }
		
		//packageName=EString
		public Assignment getPackageNameAssignment_5_1() { return cPackageNameAssignment_5_1; }
		
		//EString
		public RuleCall getPackageNameEStringParserRuleCall_5_1_0() { return cPackageNameEStringParserRuleCall_5_1_0; }
		
		//('description:' description=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'description:'
		public Keyword getDescriptionKeyword_6_0() { return cDescriptionKeyword_6_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_6_1() { return cDescriptionAssignment_6_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_6_1_0() { return cDescriptionEStringParserRuleCall_6_1_0; }
		
		//('port:' port=ELongObject)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'port:'
		public Keyword getPortKeyword_7_0() { return cPortKeyword_7_0; }
		
		//port=ELongObject
		public Assignment getPortAssignment_7_1() { return cPortAssignment_7_1; }
		
		//ELongObject
		public RuleCall getPortELongObjectParserRuleCall_7_1_0() { return cPortELongObjectParserRuleCall_7_1_0; }
		
		//('hostname:' hostname=EString)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'hostname:'
		public Keyword getHostnameKeyword_8_0() { return cHostnameKeyword_8_0; }
		
		//hostname=EString
		public Assignment getHostnameAssignment_8_1() { return cHostnameAssignment_8_1; }
		
		//EString
		public RuleCall getHostnameEStringParserRuleCall_8_1_0() { return cHostnameEStringParserRuleCall_8_1_0; }
		
		//('database:' app_database=Database)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'database:'
		public Keyword getDatabaseKeyword_9_0() { return cDatabaseKeyword_9_0; }
		
		//app_database=Database
		public Assignment getApp_databaseAssignment_9_1() { return cApp_databaseAssignment_9_1; }
		
		//Database
		public RuleCall getApp_databaseDatabaseParserRuleCall_9_1_0() { return cApp_databaseDatabaseParserRuleCall_9_1_0; }
		
		//('model:'
		//    ('user:' app_models+=User)?
		//    ('role:' app_models+=Role)?
		//)?
		public Group getGroup_10() { return cGroup_10; }
		
		//'model:'
		public Keyword getModelKeyword_10_0() { return cModelKeyword_10_0; }
		
		//('user:' app_models+=User)?
		public Group getGroup_10_1() { return cGroup_10_1; }
		
		//'user:'
		public Keyword getUserKeyword_10_1_0() { return cUserKeyword_10_1_0; }
		
		//app_models+=User
		public Assignment getApp_modelsAssignment_10_1_1() { return cApp_modelsAssignment_10_1_1; }
		
		//User
		public RuleCall getApp_modelsUserParserRuleCall_10_1_1_0() { return cApp_modelsUserParserRuleCall_10_1_1_0; }
		
		//('role:' app_models+=Role)?
		public Group getGroup_10_2() { return cGroup_10_2; }
		
		//'role:'
		public Keyword getRoleKeyword_10_2_0() { return cRoleKeyword_10_2_0; }
		
		//app_models+=Role
		public Assignment getApp_modelsAssignment_10_2_1() { return cApp_modelsAssignment_10_2_1; }
		
		//Role
		public RuleCall getApp_modelsRoleParserRuleCall_10_2_1_0() { return cApp_modelsRoleParserRuleCall_10_2_1_0; }
		
		//('security:' app_security=Security )?
		public Group getGroup_11() { return cGroup_11; }
		
		//'security:'
		public Keyword getSecurityKeyword_11_0() { return cSecurityKeyword_11_0; }
		
		//app_security=Security
		public Assignment getApp_securityAssignment_11_1() { return cApp_securityAssignment_11_1; }
		
		//Security
		public RuleCall getApp_securitySecurityParserRuleCall_11_1_0() { return cApp_securitySecurityParserRuleCall_11_1_0; }
		
		//('controller:'
		//    ('auth:' app_controllers+=Authentication)?
		//)?
		public Group getGroup_12() { return cGroup_12; }
		
		//'controller:'
		public Keyword getControllerKeyword_12_0() { return cControllerKeyword_12_0; }
		
		//('auth:' app_controllers+=Authentication)?
		public Group getGroup_12_1() { return cGroup_12_1; }
		
		//'auth:'
		public Keyword getAuthKeyword_12_1_0() { return cAuthKeyword_12_1_0; }
		
		//app_controllers+=Authentication
		public Assignment getApp_controllersAssignment_12_1_1() { return cApp_controllersAssignment_12_1_1; }
		
		//Authentication
		public RuleCall getApp_controllersAuthenticationParserRuleCall_12_1_1_0() { return cApp_controllersAuthenticationParserRuleCall_12_1_1_0; }
	}
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.securitydsl.SecurityDsl.Model");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cRoleParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cUserParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Model returns Model:
		//    Role | User;
		@Override public ParserRule getRule() { return rule; }
		
		//Role | User
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Role
		public RuleCall getRoleParserRuleCall_0() { return cRoleParserRuleCall_0; }
		
		//User
		public RuleCall getUserParserRuleCall_1() { return cUserParserRuleCall_1; }
	}
	public class ControllerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.securitydsl.SecurityDsl.Controller");
		private final RuleCall cAuthenticationParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Controller returns Controller:
		//    Authentication;
		@Override public ParserRule getRule() { return rule; }
		
		//Authentication
		public RuleCall getAuthenticationParserRuleCall() { return cAuthenticationParserRuleCall; }
	}
	public class SecurityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.securitydsl.SecurityDsl.Security");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cJWTParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cOAuth2ParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cBasicAuthenticationParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Security returns Security:
		//    JWT | OAuth2 | BasicAuthentication;
		@Override public ParserRule getRule() { return rule; }
		
		//JWT | OAuth2 | BasicAuthentication
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//JWT
		public RuleCall getJWTParserRuleCall_0() { return cJWTParserRuleCall_0; }
		
		//OAuth2
		public RuleCall getOAuth2ParserRuleCall_1() { return cOAuth2ParserRuleCall_1; }
		
		//BasicAuthentication
		public RuleCall getBasicAuthenticationParserRuleCall_2() { return cBasicAuthenticationParserRuleCall_2; }
	}
	public class DatabaseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.securitydsl.SecurityDsl.Database");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVendorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cVendorNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cVendorNameEDatabaseTypeEnumRuleCall_1_0 = (RuleCall)cVendorNameAssignment_1.eContents().get(0);
		private final Keyword cUrlKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cUrlAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cUrlEStringParserRuleCall_3_0 = (RuleCall)cUrlAssignment_3.eContents().get(0);
		private final Keyword cUsernameKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cUsernameAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cUsernameEStringParserRuleCall_5_0 = (RuleCall)cUsernameAssignment_5.eContents().get(0);
		private final Keyword cPasswordKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cPasswordAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cPasswordEStringParserRuleCall_7_0 = (RuleCall)cPasswordAssignment_7.eContents().get(0);
		
		//Database returns Database:
		//     'vendor:'  vendorName=EDatabaseType
		//     'url:' url=EString
		//     'username:' username=EString
		//     'password:' password=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//'vendor:'  vendorName=EDatabaseType
		//'url:' url=EString
		//'username:' username=EString
		//'password:' password=EString
		public Group getGroup() { return cGroup; }
		
		//'vendor:'
		public Keyword getVendorKeyword_0() { return cVendorKeyword_0; }
		
		//vendorName=EDatabaseType
		public Assignment getVendorNameAssignment_1() { return cVendorNameAssignment_1; }
		
		//EDatabaseType
		public RuleCall getVendorNameEDatabaseTypeEnumRuleCall_1_0() { return cVendorNameEDatabaseTypeEnumRuleCall_1_0; }
		
		//'url:'
		public Keyword getUrlKeyword_2() { return cUrlKeyword_2; }
		
		//url=EString
		public Assignment getUrlAssignment_3() { return cUrlAssignment_3; }
		
		//EString
		public RuleCall getUrlEStringParserRuleCall_3_0() { return cUrlEStringParserRuleCall_3_0; }
		
		//'username:'
		public Keyword getUsernameKeyword_4() { return cUsernameKeyword_4; }
		
		//username=EString
		public Assignment getUsernameAssignment_5() { return cUsernameAssignment_5; }
		
		//EString
		public RuleCall getUsernameEStringParserRuleCall_5_0() { return cUsernameEStringParserRuleCall_5_0; }
		
		//'password:'
		public Keyword getPasswordKeyword_6() { return cPasswordKeyword_6; }
		
		//password=EString
		public Assignment getPasswordAssignment_7() { return cPasswordAssignment_7; }
		
		//EString
		public RuleCall getPasswordEStringParserRuleCall_7_0() { return cPasswordEStringParserRuleCall_7_0; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.securitydsl.SecurityDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class ELongObjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.securitydsl.SecurityDsl.ELongObject");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//ELongObject returns ecore::ELongObject:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class AttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.securitydsl.SecurityDsl.Attribute");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIdentifierAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cIdentifierIdentifierKeyword_1_0 = (Keyword)cIdentifierAssignment_1.eContents().get(0);
		private final Assignment cCredentialAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cCredentialCredentialKeyword_2_0 = (Keyword)cCredentialAssignment_2.eContents().get(0);
		private final Keyword cNameKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNameEStringParserRuleCall_4_0 = (RuleCall)cNameAssignment_4.eContents().get(0);
		private final Keyword cTypeKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cTypeAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cTypeETypeEnumRuleCall_6_0 = (RuleCall)cTypeAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCollumnNameKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cCollumnNameAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cCollumnNameEStringParserRuleCall_7_1_0 = (RuleCall)cCollumnNameAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Attribute returns Attribute:
		//    '{'
		//    (identifier?='identifier')?
		//    (credential?='credential')?
		//    'name:' name=EString
		//    'type:' type=EType
		//    ('collumnName:' collumnName=EString)? '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'{'
		//(identifier?='identifier')?
		//(credential?='credential')?
		//'name:' name=EString
		//'type:' type=EType
		//('collumnName:' collumnName=EString)? '}'
		public Group getGroup() { return cGroup; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }
		
		//(identifier?='identifier')?
		public Assignment getIdentifierAssignment_1() { return cIdentifierAssignment_1; }
		
		//'identifier'
		public Keyword getIdentifierIdentifierKeyword_1_0() { return cIdentifierIdentifierKeyword_1_0; }
		
		//(credential?='credential')?
		public Assignment getCredentialAssignment_2() { return cCredentialAssignment_2; }
		
		//'credential'
		public Keyword getCredentialCredentialKeyword_2_0() { return cCredentialCredentialKeyword_2_0; }
		
		//'name:'
		public Keyword getNameKeyword_3() { return cNameKeyword_3; }
		
		//name=EString
		public Assignment getNameAssignment_4() { return cNameAssignment_4; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_4_0() { return cNameEStringParserRuleCall_4_0; }
		
		//'type:'
		public Keyword getTypeKeyword_5() { return cTypeKeyword_5; }
		
		//type=EType
		public Assignment getTypeAssignment_6() { return cTypeAssignment_6; }
		
		//EType
		public RuleCall getTypeETypeEnumRuleCall_6_0() { return cTypeETypeEnumRuleCall_6_0; }
		
		//('collumnName:' collumnName=EString)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'collumnName:'
		public Keyword getCollumnNameKeyword_7_0() { return cCollumnNameKeyword_7_0; }
		
		//collumnName=EString
		public Assignment getCollumnNameAssignment_7_1() { return cCollumnNameAssignment_7_1; }
		
		//EString
		public RuleCall getCollumnNameEStringParserRuleCall_7_1_0() { return cCollumnNameEStringParserRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class RoleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.securitydsl.SecurityDsl.Role");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRoleAction_0 = (Action)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cTableNameKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cTableNameAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cTableNameEStringParserRuleCall_1_1_0 = (RuleCall)cTableNameAssignment_1_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cAttributesKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Assignment cModel_attributesAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cModel_attributesAttributeParserRuleCall_2_2_0 = (RuleCall)cModel_attributesAssignment_2_2.eContents().get(0);
		private final Group cGroup_2_3 = (Group)cGroup_2.eContents().get(3);
		private final Keyword cCommaKeyword_2_3_0 = (Keyword)cGroup_2_3.eContents().get(0);
		private final Assignment cModel_attributesAssignment_2_3_1 = (Assignment)cGroup_2_3.eContents().get(1);
		private final RuleCall cModel_attributesAttributeParserRuleCall_2_3_1_0 = (RuleCall)cModel_attributesAssignment_2_3_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_2_4 = (Keyword)cGroup_2.eContents().get(4);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cRolesKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cRole_instancesAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cRole_instancesRoleInstanceParserRuleCall_3_2_0 = (RuleCall)cRole_instancesAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cRole_instancesAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cRole_instancesRoleInstanceParserRuleCall_3_3_1_0 = (RuleCall)cRole_instancesAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		
		//Role returns Role:
		//    {Role}
		//    ('tableName:' tableName=EString)?
		//    ('attributes:' '[' model_attributes+=Attribute ( "," model_attributes+=Attribute)* ']' )?
		//    ('roles:' '[' role_instances+=RoleInstance ( "," role_instances+=RoleInstance)* ']' )?
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{Role}
		//('tableName:' tableName=EString)?
		//('attributes:' '[' model_attributes+=Attribute ( "," model_attributes+=Attribute)* ']' )?
		//('roles:' '[' role_instances+=RoleInstance ( "," role_instances+=RoleInstance)* ']' )?
		public Group getGroup() { return cGroup; }
		
		//{Role}
		public Action getRoleAction_0() { return cRoleAction_0; }
		
		//('tableName:' tableName=EString)?
		public Group getGroup_1() { return cGroup_1; }
		
		//'tableName:'
		public Keyword getTableNameKeyword_1_0() { return cTableNameKeyword_1_0; }
		
		//tableName=EString
		public Assignment getTableNameAssignment_1_1() { return cTableNameAssignment_1_1; }
		
		//EString
		public RuleCall getTableNameEStringParserRuleCall_1_1_0() { return cTableNameEStringParserRuleCall_1_1_0; }
		
		//('attributes:' '[' model_attributes+=Attribute ( "," model_attributes+=Attribute)* ']' )?
		public Group getGroup_2() { return cGroup_2; }
		
		//'attributes:'
		public Keyword getAttributesKeyword_2_0() { return cAttributesKeyword_2_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_2_1() { return cLeftSquareBracketKeyword_2_1; }
		
		//model_attributes+=Attribute
		public Assignment getModel_attributesAssignment_2_2() { return cModel_attributesAssignment_2_2; }
		
		//Attribute
		public RuleCall getModel_attributesAttributeParserRuleCall_2_2_0() { return cModel_attributesAttributeParserRuleCall_2_2_0; }
		
		//( "," model_attributes+=Attribute)*
		public Group getGroup_2_3() { return cGroup_2_3; }
		
		//","
		public Keyword getCommaKeyword_2_3_0() { return cCommaKeyword_2_3_0; }
		
		//model_attributes+=Attribute
		public Assignment getModel_attributesAssignment_2_3_1() { return cModel_attributesAssignment_2_3_1; }
		
		//Attribute
		public RuleCall getModel_attributesAttributeParserRuleCall_2_3_1_0() { return cModel_attributesAttributeParserRuleCall_2_3_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_2_4() { return cRightSquareBracketKeyword_2_4; }
		
		//('roles:' '[' role_instances+=RoleInstance ( "," role_instances+=RoleInstance)* ']' )?
		public Group getGroup_3() { return cGroup_3; }
		
		//'roles:'
		public Keyword getRolesKeyword_3_0() { return cRolesKeyword_3_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_3_1() { return cLeftSquareBracketKeyword_3_1; }
		
		//role_instances+=RoleInstance
		public Assignment getRole_instancesAssignment_3_2() { return cRole_instancesAssignment_3_2; }
		
		//RoleInstance
		public RuleCall getRole_instancesRoleInstanceParserRuleCall_3_2_0() { return cRole_instancesRoleInstanceParserRuleCall_3_2_0; }
		
		//( "," role_instances+=RoleInstance)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//role_instances+=RoleInstance
		public Assignment getRole_instancesAssignment_3_3_1() { return cRole_instancesAssignment_3_3_1; }
		
		//RoleInstance
		public RuleCall getRole_instancesRoleInstanceParserRuleCall_3_3_1_0() { return cRole_instancesRoleInstanceParserRuleCall_3_3_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_3_4() { return cRightSquareBracketKeyword_3_4; }
	}
	public class UserElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.securitydsl.SecurityDsl.User");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cUserAction_0 = (Action)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cTableNameKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cTableNameAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cTableNameEStringParserRuleCall_1_1_0 = (RuleCall)cTableNameAssignment_1_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cAttributesKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Assignment cModel_attributesAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cModel_attributesAttributeParserRuleCall_2_2_0 = (RuleCall)cModel_attributesAssignment_2_2.eContents().get(0);
		private final Group cGroup_2_3 = (Group)cGroup_2.eContents().get(3);
		private final Keyword cCommaKeyword_2_3_0 = (Keyword)cGroup_2_3.eContents().get(0);
		private final Assignment cModel_attributesAssignment_2_3_1 = (Assignment)cGroup_2_3.eContents().get(1);
		private final RuleCall cModel_attributesAttributeParserRuleCall_2_3_1_0 = (RuleCall)cModel_attributesAssignment_2_3_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_2_4 = (Keyword)cGroup_2.eContents().get(4);
		
		//User returns User:
		//    {User}
		//    ('tableName:' tableName=EString)?
		//    ('attributes:' '[' model_attributes+=Attribute ( "," model_attributes+=Attribute)* ']' )?
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{User}
		//('tableName:' tableName=EString)?
		//('attributes:' '[' model_attributes+=Attribute ( "," model_attributes+=Attribute)* ']' )?
		public Group getGroup() { return cGroup; }
		
		//{User}
		public Action getUserAction_0() { return cUserAction_0; }
		
		//('tableName:' tableName=EString)?
		public Group getGroup_1() { return cGroup_1; }
		
		//'tableName:'
		public Keyword getTableNameKeyword_1_0() { return cTableNameKeyword_1_0; }
		
		//tableName=EString
		public Assignment getTableNameAssignment_1_1() { return cTableNameAssignment_1_1; }
		
		//EString
		public RuleCall getTableNameEStringParserRuleCall_1_1_0() { return cTableNameEStringParserRuleCall_1_1_0; }
		
		//('attributes:' '[' model_attributes+=Attribute ( "," model_attributes+=Attribute)* ']' )?
		public Group getGroup_2() { return cGroup_2; }
		
		//'attributes:'
		public Keyword getAttributesKeyword_2_0() { return cAttributesKeyword_2_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_2_1() { return cLeftSquareBracketKeyword_2_1; }
		
		//model_attributes+=Attribute
		public Assignment getModel_attributesAssignment_2_2() { return cModel_attributesAssignment_2_2; }
		
		//Attribute
		public RuleCall getModel_attributesAttributeParserRuleCall_2_2_0() { return cModel_attributesAttributeParserRuleCall_2_2_0; }
		
		//( "," model_attributes+=Attribute)*
		public Group getGroup_2_3() { return cGroup_2_3; }
		
		//","
		public Keyword getCommaKeyword_2_3_0() { return cCommaKeyword_2_3_0; }
		
		//model_attributes+=Attribute
		public Assignment getModel_attributesAssignment_2_3_1() { return cModel_attributesAssignment_2_3_1; }
		
		//Attribute
		public RuleCall getModel_attributesAttributeParserRuleCall_2_3_1_0() { return cModel_attributesAttributeParserRuleCall_2_3_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_2_4() { return cRightSquareBracketKeyword_2_4; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.securitydsl.SecurityDsl.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//    'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class RoleInstanceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.securitydsl.SecurityDsl.RoleInstance");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRoleInstanceAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cClientAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cClientClientKeyword_1_0 = (Keyword)cClientAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//RoleInstance returns RoleInstance:
		//    {RoleInstance}
		//    (client?='client')? name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{RoleInstance}
		//(client?='client')? name=EString
		public Group getGroup() { return cGroup; }
		
		//{RoleInstance}
		public Action getRoleInstanceAction_0() { return cRoleInstanceAction_0; }
		
		//(client?='client')?
		public Assignment getClientAssignment_1() { return cClientAssignment_1; }
		
		//'client'
		public Keyword getClientClientKeyword_1_0() { return cClientClientKeyword_1_0; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class EndpointElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.securitydsl.SecurityDsl.Endpoint");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cUrlKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cUrlAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cUrlEStringParserRuleCall_2_0 = (RuleCall)cUrlAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cFunctionNameKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cFunctionNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cFunctionNameEStringParserRuleCall_3_1_0 = (RuleCall)cFunctionNameAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cMethodKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cMethodAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cMethodEEndpointMethodEnumRuleCall_4_1_0 = (RuleCall)cMethodAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTypeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTypeAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cTypeEEndpointTypeEnumRuleCall_5_1_0 = (RuleCall)cTypeAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cRoleAuthoritiesKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cRole_authoritiesAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final CrossReference cRole_authoritiesRoleInstanceCrossReference_6_2_0 = (CrossReference)cRole_authoritiesAssignment_6_2.eContents().get(0);
		private final RuleCall cRole_authoritiesRoleInstanceEStringParserRuleCall_6_2_0_1 = (RuleCall)cRole_authoritiesRoleInstanceCrossReference_6_2_0.eContents().get(1);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cRole_authoritiesAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final CrossReference cRole_authoritiesRoleInstanceCrossReference_6_3_1_0 = (CrossReference)cRole_authoritiesAssignment_6_3_1.eContents().get(0);
		private final RuleCall cRole_authoritiesRoleInstanceEStringParserRuleCall_6_3_1_0_1 = (RuleCall)cRole_authoritiesRoleInstanceCrossReference_6_3_1_0.eContents().get(1);
		private final Keyword cRightSquareBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Endpoint returns Endpoint:
		//    '{'
		//        'url:' url=EString
		//        ('functionName:' functionName=EString)?
		//        ('method:' method=EEndpointMethod)?
		//        ('type:' type=EEndpointType)?
		//        ('roleAuthorities:' '[' role_authorities+=[RoleInstance|EString] ( "," role_authorities+=[RoleInstance|EString])* ']' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'{'
		//    'url:' url=EString
		//    ('functionName:' functionName=EString)?
		//    ('method:' method=EEndpointMethod)?
		//    ('type:' type=EEndpointType)?
		//    ('roleAuthorities:' '[' role_authorities+=[RoleInstance|EString] ( "," role_authorities+=[RoleInstance|EString])* ']' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }
		
		//'url:'
		public Keyword getUrlKeyword_1() { return cUrlKeyword_1; }
		
		//url=EString
		public Assignment getUrlAssignment_2() { return cUrlAssignment_2; }
		
		//EString
		public RuleCall getUrlEStringParserRuleCall_2_0() { return cUrlEStringParserRuleCall_2_0; }
		
		//('functionName:' functionName=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'functionName:'
		public Keyword getFunctionNameKeyword_3_0() { return cFunctionNameKeyword_3_0; }
		
		//functionName=EString
		public Assignment getFunctionNameAssignment_3_1() { return cFunctionNameAssignment_3_1; }
		
		//EString
		public RuleCall getFunctionNameEStringParserRuleCall_3_1_0() { return cFunctionNameEStringParserRuleCall_3_1_0; }
		
		//('method:' method=EEndpointMethod)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'method:'
		public Keyword getMethodKeyword_4_0() { return cMethodKeyword_4_0; }
		
		//method=EEndpointMethod
		public Assignment getMethodAssignment_4_1() { return cMethodAssignment_4_1; }
		
		//EEndpointMethod
		public RuleCall getMethodEEndpointMethodEnumRuleCall_4_1_0() { return cMethodEEndpointMethodEnumRuleCall_4_1_0; }
		
		//('type:' type=EEndpointType)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'type:'
		public Keyword getTypeKeyword_5_0() { return cTypeKeyword_5_0; }
		
		//type=EEndpointType
		public Assignment getTypeAssignment_5_1() { return cTypeAssignment_5_1; }
		
		//EEndpointType
		public RuleCall getTypeEEndpointTypeEnumRuleCall_5_1_0() { return cTypeEEndpointTypeEnumRuleCall_5_1_0; }
		
		//('roleAuthorities:' '[' role_authorities+=[RoleInstance|EString] ( "," role_authorities+=[RoleInstance|EString])* ']' )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'roleAuthorities:'
		public Keyword getRoleAuthoritiesKeyword_6_0() { return cRoleAuthoritiesKeyword_6_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_6_1() { return cLeftSquareBracketKeyword_6_1; }
		
		//role_authorities+=[RoleInstance|EString]
		public Assignment getRole_authoritiesAssignment_6_2() { return cRole_authoritiesAssignment_6_2; }
		
		//[RoleInstance|EString]
		public CrossReference getRole_authoritiesRoleInstanceCrossReference_6_2_0() { return cRole_authoritiesRoleInstanceCrossReference_6_2_0; }
		
		//EString
		public RuleCall getRole_authoritiesRoleInstanceEStringParserRuleCall_6_2_0_1() { return cRole_authoritiesRoleInstanceEStringParserRuleCall_6_2_0_1; }
		
		//( "," role_authorities+=[RoleInstance|EString])*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//role_authorities+=[RoleInstance|EString]
		public Assignment getRole_authoritiesAssignment_6_3_1() { return cRole_authoritiesAssignment_6_3_1; }
		
		//[RoleInstance|EString]
		public CrossReference getRole_authoritiesRoleInstanceCrossReference_6_3_1_0() { return cRole_authoritiesRoleInstanceCrossReference_6_3_1_0; }
		
		//EString
		public RuleCall getRole_authoritiesRoleInstanceEStringParserRuleCall_6_3_1_0_1() { return cRole_authoritiesRoleInstanceEStringParserRuleCall_6_3_1_0_1; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_6_4() { return cRightSquareBracketKeyword_6_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class AuthenticationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.securitydsl.SecurityDsl.Authentication");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAuthenticationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cNameKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cPathKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPathAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPathEStringParserRuleCall_4_0 = (RuleCall)cPathAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cEndpointsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cController_endpointsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cController_endpointsEndpointParserRuleCall_5_2_0 = (RuleCall)cController_endpointsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cController_endpointsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cController_endpointsEndpointParserRuleCall_5_3_1_0 = (RuleCall)cController_endpointsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		
		//Authentication returns Authentication:
		//    {Authentication}
		//    'name:' name=EString
		//    'path:' path=EString
		//    ('endpoints:' '[' controller_endpoints+=Endpoint ( "," controller_endpoints+=Endpoint)* ']' )?;
		@Override public ParserRule getRule() { return rule; }
		
		//{Authentication}
		//'name:' name=EString
		//'path:' path=EString
		//('endpoints:' '[' controller_endpoints+=Endpoint ( "," controller_endpoints+=Endpoint)* ']' )?
		public Group getGroup() { return cGroup; }
		
		//{Authentication}
		public Action getAuthenticationAction_0() { return cAuthenticationAction_0; }
		
		//'name:'
		public Keyword getNameKeyword_1() { return cNameKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'path:'
		public Keyword getPathKeyword_3() { return cPathKeyword_3; }
		
		//path=EString
		public Assignment getPathAssignment_4() { return cPathAssignment_4; }
		
		//EString
		public RuleCall getPathEStringParserRuleCall_4_0() { return cPathEStringParserRuleCall_4_0; }
		
		//('endpoints:' '[' controller_endpoints+=Endpoint ( "," controller_endpoints+=Endpoint)* ']' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'endpoints:'
		public Keyword getEndpointsKeyword_5_0() { return cEndpointsKeyword_5_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_5_1() { return cLeftSquareBracketKeyword_5_1; }
		
		//controller_endpoints+=Endpoint
		public Assignment getController_endpointsAssignment_5_2() { return cController_endpointsAssignment_5_2; }
		
		//Endpoint
		public RuleCall getController_endpointsEndpointParserRuleCall_5_2_0() { return cController_endpointsEndpointParserRuleCall_5_2_0; }
		
		//( "," controller_endpoints+=Endpoint)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//controller_endpoints+=Endpoint
		public Assignment getController_endpointsAssignment_5_3_1() { return cController_endpointsAssignment_5_3_1; }
		
		//Endpoint
		public RuleCall getController_endpointsEndpointParserRuleCall_5_3_1_0() { return cController_endpointsEndpointParserRuleCall_5_3_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_5_4() { return cRightSquareBracketKeyword_5_4; }
	}
	public class JWTElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.securitydsl.SecurityDsl.JWT");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cJwtKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cHeaderKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cSignatureAlgorithmKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSignatureAlgorithmAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cSignatureAlgorithmEStringParserRuleCall_3_0 = (RuleCall)cSignatureAlgorithmAssignment_3.eContents().get(0);
		private final Keyword cPayloadKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cClaimsKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftSquareBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cRegisteredclaimsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cRegisteredclaimsRegisteredClaimsParserRuleCall_7_0 = (RuleCall)cRegisteredclaimsAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCommaKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cJwt_claimsAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cJwt_claimsClaimParserRuleCall_8_1_0 = (RuleCall)cJwt_claimsAssignment_8_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cSignatureKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cSecretKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Assignment cSecretAssignment_10_2 = (Assignment)cGroup_10.eContents().get(2);
		private final RuleCall cSecretEStringParserRuleCall_10_2_0 = (RuleCall)cSecretAssignment_10_2.eContents().get(0);
		
		//JWT returns JWT:
		//    'jwt:'
		//    'header:'
		//    'signatureAlgorithm:' signatureAlgorithm=EString
		//    'payload:'
		//    'claims:' '['registeredclaims=RegisteredClaims (( "," jwt_claims+=Claim)*)?']'
		//    ('signature:'
		//    'secret:' secret=EString)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'jwt:'
		//'header:'
		//'signatureAlgorithm:' signatureAlgorithm=EString
		//'payload:'
		//'claims:' '['registeredclaims=RegisteredClaims (( "," jwt_claims+=Claim)*)?']'
		//('signature:'
		//'secret:' secret=EString)?
		public Group getGroup() { return cGroup; }
		
		//'jwt:'
		public Keyword getJwtKeyword_0() { return cJwtKeyword_0; }
		
		//'header:'
		public Keyword getHeaderKeyword_1() { return cHeaderKeyword_1; }
		
		//'signatureAlgorithm:'
		public Keyword getSignatureAlgorithmKeyword_2() { return cSignatureAlgorithmKeyword_2; }
		
		//signatureAlgorithm=EString
		public Assignment getSignatureAlgorithmAssignment_3() { return cSignatureAlgorithmAssignment_3; }
		
		//EString
		public RuleCall getSignatureAlgorithmEStringParserRuleCall_3_0() { return cSignatureAlgorithmEStringParserRuleCall_3_0; }
		
		//'payload:'
		public Keyword getPayloadKeyword_4() { return cPayloadKeyword_4; }
		
		//'claims:'
		public Keyword getClaimsKeyword_5() { return cClaimsKeyword_5; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_6() { return cLeftSquareBracketKeyword_6; }
		
		//registeredclaims=RegisteredClaims
		public Assignment getRegisteredclaimsAssignment_7() { return cRegisteredclaimsAssignment_7; }
		
		//RegisteredClaims
		public RuleCall getRegisteredclaimsRegisteredClaimsParserRuleCall_7_0() { return cRegisteredclaimsRegisteredClaimsParserRuleCall_7_0; }
		
		//(( "," jwt_claims+=Claim)*)?
		public Group getGroup_8() { return cGroup_8; }
		
		//","
		public Keyword getCommaKeyword_8_0() { return cCommaKeyword_8_0; }
		
		//jwt_claims+=Claim
		public Assignment getJwt_claimsAssignment_8_1() { return cJwt_claimsAssignment_8_1; }
		
		//Claim
		public RuleCall getJwt_claimsClaimParserRuleCall_8_1_0() { return cJwt_claimsClaimParserRuleCall_8_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_9() { return cRightSquareBracketKeyword_9; }
		
		//('signature:'
		//'secret:' secret=EString)?
		public Group getGroup_10() { return cGroup_10; }
		
		//'signature:'
		public Keyword getSignatureKeyword_10_0() { return cSignatureKeyword_10_0; }
		
		//'secret:'
		public Keyword getSecretKeyword_10_1() { return cSecretKeyword_10_1; }
		
		//secret=EString
		public Assignment getSecretAssignment_10_2() { return cSecretAssignment_10_2; }
		
		//EString
		public RuleCall getSecretEStringParserRuleCall_10_2_0() { return cSecretEStringParserRuleCall_10_2_0; }
	}
	public class ClaimElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.securitydsl.SecurityDsl.Claim");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cTypeEClaimTypeEnumRuleCall_1_0_0 = (RuleCall)cTypeAssignment_1_0.eContents().get(0);
		private final Keyword cCommaKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cClaim_attributeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cClaim_attributeAttributeCrossReference_4_0 = (CrossReference)cClaim_attributeAssignment_4.eContents().get(0);
		private final RuleCall cClaim_attributeAttributeEStringParserRuleCall_4_0_1 = (RuleCall)cClaim_attributeAttributeCrossReference_4_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Claim returns Claim:
		//    '{'
		//        (type=EClaimType',')?
		//        name=EString ':' claim_attribute=[Attribute|EString]
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'{'
		//    (type=EClaimType',')?
		//    name=EString ':' claim_attribute=[Attribute|EString]
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }
		
		//(type=EClaimType',')?
		public Group getGroup_1() { return cGroup_1; }
		
		//type=EClaimType
		public Assignment getTypeAssignment_1_0() { return cTypeAssignment_1_0; }
		
		//EClaimType
		public RuleCall getTypeEClaimTypeEnumRuleCall_1_0_0() { return cTypeEClaimTypeEnumRuleCall_1_0_0; }
		
		//','
		public Keyword getCommaKeyword_1_1() { return cCommaKeyword_1_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//claim_attribute=[Attribute|EString]
		public Assignment getClaim_attributeAssignment_4() { return cClaim_attributeAssignment_4; }
		
		//[Attribute|EString]
		public CrossReference getClaim_attributeAttributeCrossReference_4_0() { return cClaim_attributeAttributeCrossReference_4_0; }
		
		//EString
		public RuleCall getClaim_attributeAttributeEStringParserRuleCall_4_0_1() { return cClaim_attributeAttributeEStringParserRuleCall_4_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class RegisteredClaimsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.securitydsl.SecurityDsl.RegisteredClaims");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cREGISTEREDKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cExpirationTimeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cExpirationTimeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cExpirationTimeEIntParserRuleCall_3_0 = (RuleCall)cExpirationTimeAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Keyword cREGISTEREDKeyword_5_2 = (Keyword)cGroup_5.eContents().get(2);
		private final Keyword cIssuerKeyword_5_3 = (Keyword)cGroup_5.eContents().get(3);
		private final Assignment cIssuerAssignment_5_4 = (Assignment)cGroup_5.eContents().get(4);
		private final RuleCall cIssuerEStringParserRuleCall_5_4_0 = (RuleCall)cIssuerAssignment_5_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_5 = (Keyword)cGroup_5.eContents().get(5);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Keyword cREGISTEREDKeyword_6_2 = (Keyword)cGroup_6.eContents().get(2);
		private final Keyword cAudienceKeyword_6_3 = (Keyword)cGroup_6.eContents().get(3);
		private final Assignment cAudienceAssignment_6_4 = (Assignment)cGroup_6.eContents().get(4);
		private final RuleCall cAudienceEStringParserRuleCall_6_4_0 = (RuleCall)cAudienceAssignment_6_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_5 = (Keyword)cGroup_6.eContents().get(5);
		
		//RegisteredClaims returns RegisteredClaims:
		//    '{'
		//        'REGISTERED,'
		//        'expirationTime:' expirationTime=EInt
		//    '}'
		//    (',''{'
		//        'REGISTERED,'
		//        'issuer:' issuer=EString
		//    '}')?
		//    (',''{'
		//        'REGISTERED,'
		//        'audience:' audience=EString
		//    '}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//'{'
		//    'REGISTERED,'
		//    'expirationTime:' expirationTime=EInt
		//'}'
		//(',''{'
		//    'REGISTERED,'
		//    'issuer:' issuer=EString
		//'}')?
		//(',''{'
		//    'REGISTERED,'
		//    'audience:' audience=EString
		//'}')?
		public Group getGroup() { return cGroup; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }
		
		//'REGISTERED,'
		public Keyword getREGISTEREDKeyword_1() { return cREGISTEREDKeyword_1; }
		
		//'expirationTime:'
		public Keyword getExpirationTimeKeyword_2() { return cExpirationTimeKeyword_2; }
		
		//expirationTime=EInt
		public Assignment getExpirationTimeAssignment_3() { return cExpirationTimeAssignment_3; }
		
		//EInt
		public RuleCall getExpirationTimeEIntParserRuleCall_3_0() { return cExpirationTimeEIntParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
		
		//(',''{'
		//    'REGISTERED,'
		//    'issuer:' issuer=EString
		//'}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//','
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//'REGISTERED,'
		public Keyword getREGISTEREDKeyword_5_2() { return cREGISTEREDKeyword_5_2; }
		
		//'issuer:'
		public Keyword getIssuerKeyword_5_3() { return cIssuerKeyword_5_3; }
		
		//issuer=EString
		public Assignment getIssuerAssignment_5_4() { return cIssuerAssignment_5_4; }
		
		//EString
		public RuleCall getIssuerEStringParserRuleCall_5_4_0() { return cIssuerEStringParserRuleCall_5_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_5() { return cRightCurlyBracketKeyword_5_5; }
		
		//(',''{'
		//    'REGISTERED,'
		//    'audience:' audience=EString
		//'}')?
		public Group getGroup_6() { return cGroup_6; }
		
		//','
		public Keyword getCommaKeyword_6_0() { return cCommaKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//'REGISTERED,'
		public Keyword getREGISTEREDKeyword_6_2() { return cREGISTEREDKeyword_6_2; }
		
		//'audience:'
		public Keyword getAudienceKeyword_6_3() { return cAudienceKeyword_6_3; }
		
		//audience=EString
		public Assignment getAudienceAssignment_6_4() { return cAudienceAssignment_6_4; }
		
		//EString
		public RuleCall getAudienceEStringParserRuleCall_6_4_0() { return cAudienceEStringParserRuleCall_6_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_5() { return cRightCurlyBracketKeyword_6_5; }
	}
	public class OAuth2Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.securitydsl.SecurityDsl.OAuth2");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cOAuth2Action_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cOAuth20Keyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//OAuth2 returns OAuth2:
		//    {OAuth2} 'OAuth2.0';
		@Override public ParserRule getRule() { return rule; }
		
		//{OAuth2} 'OAuth2.0'
		public Group getGroup() { return cGroup; }
		
		//{OAuth2}
		public Action getOAuth2Action_0() { return cOAuth2Action_0; }
		
		//'OAuth2.0'
		public Keyword getOAuth20Keyword_1() { return cOAuth20Keyword_1; }
	}
	public class BasicAuthenticationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.securitydsl.SecurityDsl.BasicAuthentication");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBasicAuthenticationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBasicAuthenticationKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//BasicAuthentication returns BasicAuthentication:
		//    {BasicAuthentication} 'basicAuthentication';
		@Override public ParserRule getRule() { return rule; }
		
		//{BasicAuthentication} 'basicAuthentication'
		public Group getGroup() { return cGroup; }
		
		//{BasicAuthentication}
		public Action getBasicAuthenticationAction_0() { return cBasicAuthenticationAction_0; }
		
		//'basicAuthentication'
		public Keyword getBasicAuthenticationKeyword_1() { return cBasicAuthenticationKeyword_1; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.securitydsl.SecurityDsl.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	
	public class EDatabaseTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.securitydsl.SecurityDsl.EDatabaseType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cPostgreSQLEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cPostgreSQLPostgreSQLKeyword_0_0 = (Keyword)cPostgreSQLEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cOracleEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cOracleOracleKeyword_1_0 = (Keyword)cOracleEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cMySQLEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cMySQLMySQLKeyword_2_0 = (Keyword)cMySQLEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum EDatabaseType returns EDatabaseType:
		//                PostgreSQL = 'PostgreSQL' | Oracle = 'Oracle' | MySQL = 'MySQL';
		public EnumRule getRule() { return rule; }
		
		//PostgreSQL = 'PostgreSQL' | Oracle = 'Oracle' | MySQL = 'MySQL'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//PostgreSQL = 'PostgreSQL'
		public EnumLiteralDeclaration getPostgreSQLEnumLiteralDeclaration_0() { return cPostgreSQLEnumLiteralDeclaration_0; }
		
		//'PostgreSQL'
		public Keyword getPostgreSQLPostgreSQLKeyword_0_0() { return cPostgreSQLPostgreSQLKeyword_0_0; }
		
		//Oracle = 'Oracle'
		public EnumLiteralDeclaration getOracleEnumLiteralDeclaration_1() { return cOracleEnumLiteralDeclaration_1; }
		
		//'Oracle'
		public Keyword getOracleOracleKeyword_1_0() { return cOracleOracleKeyword_1_0; }
		
		//MySQL = 'MySQL'
		public EnumLiteralDeclaration getMySQLEnumLiteralDeclaration_2() { return cMySQLEnumLiteralDeclaration_2; }
		
		//'MySQL'
		public Keyword getMySQLMySQLKeyword_2_0() { return cMySQLMySQLKeyword_2_0; }
	}
	public class ETypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.securitydsl.SecurityDsl.EType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cStringEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cStringStringKeyword_0_0 = (Keyword)cStringEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cFloatEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cFloatFloatKeyword_1_0 = (Keyword)cFloatEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cLongEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cLongLongKeyword_2_0 = (Keyword)cLongEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cIntegerEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cIntegerIntegerKeyword_3_0 = (Keyword)cIntegerEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cCharEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cCharCharKeyword_4_0 = (Keyword)cCharEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cDoubleEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cDoubleDoubleKeyword_5_0 = (Keyword)cDoubleEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cDateTimeEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cDateTimeDateTimeKeyword_6_0 = (Keyword)cDateTimeEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cDateEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cDateDateKeyword_7_0 = (Keyword)cDateEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cIntEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cIntIntKeyword_8_0 = (Keyword)cIntEnumLiteralDeclaration_8.eContents().get(0);
		
		//enum EType returns EType:
		//                String = 'String' | Float = 'Float' | Long = 'Long' | Integer = 'Integer' | char = 'char' | Double = 'Double' | DateTime = 'DateTime' | Date = 'Date' | int = 'int';
		public EnumRule getRule() { return rule; }
		
		//String = 'String' | Float = 'Float' | Long = 'Long' | Integer = 'Integer' | char = 'char' | Double = 'Double' | DateTime = 'DateTime' | Date = 'Date' | int = 'int'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//String = 'String'
		public EnumLiteralDeclaration getStringEnumLiteralDeclaration_0() { return cStringEnumLiteralDeclaration_0; }
		
		//'String'
		public Keyword getStringStringKeyword_0_0() { return cStringStringKeyword_0_0; }
		
		//Float = 'Float'
		public EnumLiteralDeclaration getFloatEnumLiteralDeclaration_1() { return cFloatEnumLiteralDeclaration_1; }
		
		//'Float'
		public Keyword getFloatFloatKeyword_1_0() { return cFloatFloatKeyword_1_0; }
		
		//Long = 'Long'
		public EnumLiteralDeclaration getLongEnumLiteralDeclaration_2() { return cLongEnumLiteralDeclaration_2; }
		
		//'Long'
		public Keyword getLongLongKeyword_2_0() { return cLongLongKeyword_2_0; }
		
		//Integer = 'Integer'
		public EnumLiteralDeclaration getIntegerEnumLiteralDeclaration_3() { return cIntegerEnumLiteralDeclaration_3; }
		
		//'Integer'
		public Keyword getIntegerIntegerKeyword_3_0() { return cIntegerIntegerKeyword_3_0; }
		
		//char = 'char'
		public EnumLiteralDeclaration getCharEnumLiteralDeclaration_4() { return cCharEnumLiteralDeclaration_4; }
		
		//'char'
		public Keyword getCharCharKeyword_4_0() { return cCharCharKeyword_4_0; }
		
		//Double = 'Double'
		public EnumLiteralDeclaration getDoubleEnumLiteralDeclaration_5() { return cDoubleEnumLiteralDeclaration_5; }
		
		//'Double'
		public Keyword getDoubleDoubleKeyword_5_0() { return cDoubleDoubleKeyword_5_0; }
		
		//DateTime = 'DateTime'
		public EnumLiteralDeclaration getDateTimeEnumLiteralDeclaration_6() { return cDateTimeEnumLiteralDeclaration_6; }
		
		//'DateTime'
		public Keyword getDateTimeDateTimeKeyword_6_0() { return cDateTimeDateTimeKeyword_6_0; }
		
		//Date = 'Date'
		public EnumLiteralDeclaration getDateEnumLiteralDeclaration_7() { return cDateEnumLiteralDeclaration_7; }
		
		//'Date'
		public Keyword getDateDateKeyword_7_0() { return cDateDateKeyword_7_0; }
		
		//int = 'int'
		public EnumLiteralDeclaration getIntEnumLiteralDeclaration_8() { return cIntEnumLiteralDeclaration_8; }
		
		//'int'
		public Keyword getIntIntKeyword_8_0() { return cIntIntKeyword_8_0; }
	}
	public class EEndpointMethodElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.securitydsl.SecurityDsl.EEndpointMethod");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cGETEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cGETGETKeyword_0_0 = (Keyword)cGETEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cPOSTEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cPOSTPOSTKeyword_1_0 = (Keyword)cPOSTEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cPUTEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cPUTPUTKeyword_2_0 = (Keyword)cPUTEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cDELETEEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cDELETEDELETEKeyword_3_0 = (Keyword)cDELETEEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum EEndpointMethod returns EEndpointMethod:
		//                GET = 'GET' | POST = 'POST' | PUT = 'PUT' | DELETE = 'DELETE';
		public EnumRule getRule() { return rule; }
		
		//GET = 'GET' | POST = 'POST' | PUT = 'PUT' | DELETE = 'DELETE'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//GET = 'GET'
		public EnumLiteralDeclaration getGETEnumLiteralDeclaration_0() { return cGETEnumLiteralDeclaration_0; }
		
		//'GET'
		public Keyword getGETGETKeyword_0_0() { return cGETGETKeyword_0_0; }
		
		//POST = 'POST'
		public EnumLiteralDeclaration getPOSTEnumLiteralDeclaration_1() { return cPOSTEnumLiteralDeclaration_1; }
		
		//'POST'
		public Keyword getPOSTPOSTKeyword_1_0() { return cPOSTPOSTKeyword_1_0; }
		
		//PUT = 'PUT'
		public EnumLiteralDeclaration getPUTEnumLiteralDeclaration_2() { return cPUTEnumLiteralDeclaration_2; }
		
		//'PUT'
		public Keyword getPUTPUTKeyword_2_0() { return cPUTPUTKeyword_2_0; }
		
		//DELETE = 'DELETE'
		public EnumLiteralDeclaration getDELETEEnumLiteralDeclaration_3() { return cDELETEEnumLiteralDeclaration_3; }
		
		//'DELETE'
		public Keyword getDELETEDELETEKeyword_3_0() { return cDELETEDELETEKeyword_3_0; }
	}
	public class EEndpointTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.securitydsl.SecurityDsl.EEndpointType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cREGISTRATIONEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cREGISTRATIONREGISTRATIONKeyword_0_0 = (Keyword)cREGISTRATIONEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cLOGINEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cLOGINLOGINKeyword_1_0 = (Keyword)cLOGINEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cLOGOUTEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cLOGOUTLOGOUTKeyword_2_0 = (Keyword)cLOGOUTEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cOTHEREnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cOTHEROTHERKeyword_3_0 = (Keyword)cOTHEREnumLiteralDeclaration_3.eContents().get(0);
		
		//enum EEndpointType returns EEndpointType:
		//                REGISTRATION = 'REGISTRATION' | LOGIN = 'LOGIN' | LOGOUT = 'LOGOUT' | OTHER = 'OTHER';
		public EnumRule getRule() { return rule; }
		
		//REGISTRATION = 'REGISTRATION' | LOGIN = 'LOGIN' | LOGOUT = 'LOGOUT' | OTHER = 'OTHER'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//REGISTRATION = 'REGISTRATION'
		public EnumLiteralDeclaration getREGISTRATIONEnumLiteralDeclaration_0() { return cREGISTRATIONEnumLiteralDeclaration_0; }
		
		//'REGISTRATION'
		public Keyword getREGISTRATIONREGISTRATIONKeyword_0_0() { return cREGISTRATIONREGISTRATIONKeyword_0_0; }
		
		//LOGIN = 'LOGIN'
		public EnumLiteralDeclaration getLOGINEnumLiteralDeclaration_1() { return cLOGINEnumLiteralDeclaration_1; }
		
		//'LOGIN'
		public Keyword getLOGINLOGINKeyword_1_0() { return cLOGINLOGINKeyword_1_0; }
		
		//LOGOUT = 'LOGOUT'
		public EnumLiteralDeclaration getLOGOUTEnumLiteralDeclaration_2() { return cLOGOUTEnumLiteralDeclaration_2; }
		
		//'LOGOUT'
		public Keyword getLOGOUTLOGOUTKeyword_2_0() { return cLOGOUTLOGOUTKeyword_2_0; }
		
		//OTHER = 'OTHER'
		public EnumLiteralDeclaration getOTHEREnumLiteralDeclaration_3() { return cOTHEREnumLiteralDeclaration_3; }
		
		//'OTHER'
		public Keyword getOTHEROTHERKeyword_3_0() { return cOTHEROTHERKeyword_3_0; }
	}
	public class EClaimTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.securitydsl.SecurityDsl.EClaimType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cPRIVATEEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cPRIVATEPRIVATEKeyword_0_0 = (Keyword)cPRIVATEEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cPUBLICEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cPUBLICPUBLICKeyword_1_0 = (Keyword)cPUBLICEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cREGISTEREDEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cREGISTEREDREGISTEREDKeyword_2_0 = (Keyword)cREGISTEREDEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum EClaimType returns EClaimType:
		//                PRIVATE = 'PRIVATE' | PUBLIC = 'PUBLIC' | REGISTERED = 'REGISTERED';
		public EnumRule getRule() { return rule; }
		
		//PRIVATE = 'PRIVATE' | PUBLIC = 'PUBLIC' | REGISTERED = 'REGISTERED'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//PRIVATE = 'PRIVATE'
		public EnumLiteralDeclaration getPRIVATEEnumLiteralDeclaration_0() { return cPRIVATEEnumLiteralDeclaration_0; }
		
		//'PRIVATE'
		public Keyword getPRIVATEPRIVATEKeyword_0_0() { return cPRIVATEPRIVATEKeyword_0_0; }
		
		//PUBLIC = 'PUBLIC'
		public EnumLiteralDeclaration getPUBLICEnumLiteralDeclaration_1() { return cPUBLICEnumLiteralDeclaration_1; }
		
		//'PUBLIC'
		public Keyword getPUBLICPUBLICKeyword_1_0() { return cPUBLICPUBLICKeyword_1_0; }
		
		//REGISTERED = 'REGISTERED'
		public EnumLiteralDeclaration getREGISTEREDEnumLiteralDeclaration_2() { return cREGISTEREDEnumLiteralDeclaration_2; }
		
		//'REGISTERED'
		public Keyword getREGISTEREDREGISTEREDKeyword_2_0() { return cREGISTEREDREGISTEREDKeyword_2_0; }
	}
	
	private final ApplicationElements pApplication;
	private final ModelElements pModel;
	private final ControllerElements pController;
	private final SecurityElements pSecurity;
	private final DatabaseElements pDatabase;
	private final EStringElements pEString;
	private final ELongObjectElements pELongObject;
	private final EDatabaseTypeElements eEDatabaseType;
	private final AttributeElements pAttribute;
	private final RoleElements pRole;
	private final UserElements pUser;
	private final ETypeElements eEType;
	private final EBooleanElements pEBoolean;
	private final RoleInstanceElements pRoleInstance;
	private final EndpointElements pEndpoint;
	private final AuthenticationElements pAuthentication;
	private final EEndpointMethodElements eEEndpointMethod;
	private final EEndpointTypeElements eEEndpointType;
	private final JWTElements pJWT;
	private final ClaimElements pClaim;
	private final RegisteredClaimsElements pRegisteredClaims;
	private final EClaimTypeElements eEClaimType;
	private final OAuth2Elements pOAuth2;
	private final BasicAuthenticationElements pBasicAuthentication;
	private final EIntElements pEInt;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public SecurityDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pApplication = new ApplicationElements();
		this.pModel = new ModelElements();
		this.pController = new ControllerElements();
		this.pSecurity = new SecurityElements();
		this.pDatabase = new DatabaseElements();
		this.pEString = new EStringElements();
		this.pELongObject = new ELongObjectElements();
		this.eEDatabaseType = new EDatabaseTypeElements();
		this.pAttribute = new AttributeElements();
		this.pRole = new RoleElements();
		this.pUser = new UserElements();
		this.eEType = new ETypeElements();
		this.pEBoolean = new EBooleanElements();
		this.pRoleInstance = new RoleInstanceElements();
		this.pEndpoint = new EndpointElements();
		this.pAuthentication = new AuthenticationElements();
		this.eEEndpointMethod = new EEndpointMethodElements();
		this.eEEndpointType = new EEndpointTypeElements();
		this.pJWT = new JWTElements();
		this.pClaim = new ClaimElements();
		this.pRegisteredClaims = new RegisteredClaimsElements();
		this.eEClaimType = new EClaimTypeElements();
		this.pOAuth2 = new OAuth2Elements();
		this.pBasicAuthentication = new BasicAuthenticationElements();
		this.pEInt = new EIntElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.securitydsl.SecurityDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Application returns Application:
	//    {Application}
	//    'application:'
	//    ('artifact:' artifact=EString)?
	//    ('name:' name=EString)?
	//    ('group:' group=EString)?
	//    ('packageName:' packageName=EString)?
	//    ('description:' description=EString)?
	//    ('port:' port=ELongObject)?
	//    ('hostname:' hostname=EString)?
	//    ('database:' app_database=Database)?
	//    ('model:'
	//        ('user:' app_models+=User)?
	//        ('role:' app_models+=Role)?
	//    )?
	//    ('security:' app_security=Security )?
	//    ('controller:'
	//        ('auth:' app_controllers+=Authentication)?
	//    )?
	//    ;
	public ApplicationElements getApplicationAccess() {
		return pApplication;
	}
	
	public ParserRule getApplicationRule() {
		return getApplicationAccess().getRule();
	}
	
	//Model returns Model:
	//    Role | User;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Controller returns Controller:
	//    Authentication;
	public ControllerElements getControllerAccess() {
		return pController;
	}
	
	public ParserRule getControllerRule() {
		return getControllerAccess().getRule();
	}
	
	//Security returns Security:
	//    JWT | OAuth2 | BasicAuthentication;
	public SecurityElements getSecurityAccess() {
		return pSecurity;
	}
	
	public ParserRule getSecurityRule() {
		return getSecurityAccess().getRule();
	}
	
	//Database returns Database:
	//     'vendor:'  vendorName=EDatabaseType
	//     'url:' url=EString
	//     'username:' username=EString
	//     'password:' password=EString;
	public DatabaseElements getDatabaseAccess() {
		return pDatabase;
	}
	
	public ParserRule getDatabaseRule() {
		return getDatabaseAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//ELongObject returns ecore::ELongObject:
	//    '-'? INT;
	public ELongObjectElements getELongObjectAccess() {
		return pELongObject;
	}
	
	public ParserRule getELongObjectRule() {
		return getELongObjectAccess().getRule();
	}
	
	//enum EDatabaseType returns EDatabaseType:
	//                PostgreSQL = 'PostgreSQL' | Oracle = 'Oracle' | MySQL = 'MySQL';
	public EDatabaseTypeElements getEDatabaseTypeAccess() {
		return eEDatabaseType;
	}
	
	public EnumRule getEDatabaseTypeRule() {
		return getEDatabaseTypeAccess().getRule();
	}
	
	//Attribute returns Attribute:
	//    '{'
	//    (identifier?='identifier')?
	//    (credential?='credential')?
	//    'name:' name=EString
	//    'type:' type=EType
	//    ('collumnName:' collumnName=EString)? '}';
	public AttributeElements getAttributeAccess() {
		return pAttribute;
	}
	
	public ParserRule getAttributeRule() {
		return getAttributeAccess().getRule();
	}
	
	//Role returns Role:
	//    {Role}
	//    ('tableName:' tableName=EString)?
	//    ('attributes:' '[' model_attributes+=Attribute ( "," model_attributes+=Attribute)* ']' )?
	//    ('roles:' '[' role_instances+=RoleInstance ( "," role_instances+=RoleInstance)* ']' )?
	//    ;
	public RoleElements getRoleAccess() {
		return pRole;
	}
	
	public ParserRule getRoleRule() {
		return getRoleAccess().getRule();
	}
	
	//User returns User:
	//    {User}
	//    ('tableName:' tableName=EString)?
	//    ('attributes:' '[' model_attributes+=Attribute ( "," model_attributes+=Attribute)* ']' )?
	//    ;
	public UserElements getUserAccess() {
		return pUser;
	}
	
	public ParserRule getUserRule() {
		return getUserAccess().getRule();
	}
	
	//enum EType returns EType:
	//                String = 'String' | Float = 'Float' | Long = 'Long' | Integer = 'Integer' | char = 'char' | Double = 'Double' | DateTime = 'DateTime' | Date = 'Date' | int = 'int';
	public ETypeElements getETypeAccess() {
		return eEType;
	}
	
	public EnumRule getETypeRule() {
		return getETypeAccess().getRule();
	}
	
	//EBoolean returns ecore::EBoolean:
	//    'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//RoleInstance returns RoleInstance:
	//    {RoleInstance}
	//    (client?='client')? name=EString;
	public RoleInstanceElements getRoleInstanceAccess() {
		return pRoleInstance;
	}
	
	public ParserRule getRoleInstanceRule() {
		return getRoleInstanceAccess().getRule();
	}
	
	//Endpoint returns Endpoint:
	//    '{'
	//        'url:' url=EString
	//        ('functionName:' functionName=EString)?
	//        ('method:' method=EEndpointMethod)?
	//        ('type:' type=EEndpointType)?
	//        ('roleAuthorities:' '[' role_authorities+=[RoleInstance|EString] ( "," role_authorities+=[RoleInstance|EString])* ']' )?
	//    '}';
	public EndpointElements getEndpointAccess() {
		return pEndpoint;
	}
	
	public ParserRule getEndpointRule() {
		return getEndpointAccess().getRule();
	}
	
	//Authentication returns Authentication:
	//    {Authentication}
	//    'name:' name=EString
	//    'path:' path=EString
	//    ('endpoints:' '[' controller_endpoints+=Endpoint ( "," controller_endpoints+=Endpoint)* ']' )?;
	public AuthenticationElements getAuthenticationAccess() {
		return pAuthentication;
	}
	
	public ParserRule getAuthenticationRule() {
		return getAuthenticationAccess().getRule();
	}
	
	//enum EEndpointMethod returns EEndpointMethod:
	//                GET = 'GET' | POST = 'POST' | PUT = 'PUT' | DELETE = 'DELETE';
	public EEndpointMethodElements getEEndpointMethodAccess() {
		return eEEndpointMethod;
	}
	
	public EnumRule getEEndpointMethodRule() {
		return getEEndpointMethodAccess().getRule();
	}
	
	//enum EEndpointType returns EEndpointType:
	//                REGISTRATION = 'REGISTRATION' | LOGIN = 'LOGIN' | LOGOUT = 'LOGOUT' | OTHER = 'OTHER';
	public EEndpointTypeElements getEEndpointTypeAccess() {
		return eEEndpointType;
	}
	
	public EnumRule getEEndpointTypeRule() {
		return getEEndpointTypeAccess().getRule();
	}
	
	//JWT returns JWT:
	//    'jwt:'
	//    'header:'
	//    'signatureAlgorithm:' signatureAlgorithm=EString
	//    'payload:'
	//    'claims:' '['registeredclaims=RegisteredClaims (( "," jwt_claims+=Claim)*)?']'
	//    ('signature:'
	//    'secret:' secret=EString)?;
	public JWTElements getJWTAccess() {
		return pJWT;
	}
	
	public ParserRule getJWTRule() {
		return getJWTAccess().getRule();
	}
	
	//Claim returns Claim:
	//    '{'
	//        (type=EClaimType',')?
	//        name=EString ':' claim_attribute=[Attribute|EString]
	//    '}';
	public ClaimElements getClaimAccess() {
		return pClaim;
	}
	
	public ParserRule getClaimRule() {
		return getClaimAccess().getRule();
	}
	
	//RegisteredClaims returns RegisteredClaims:
	//    '{'
	//        'REGISTERED,'
	//        'expirationTime:' expirationTime=EInt
	//    '}'
	//    (',''{'
	//        'REGISTERED,'
	//        'issuer:' issuer=EString
	//    '}')?
	//    (',''{'
	//        'REGISTERED,'
	//        'audience:' audience=EString
	//    '}')?;
	public RegisteredClaimsElements getRegisteredClaimsAccess() {
		return pRegisteredClaims;
	}
	
	public ParserRule getRegisteredClaimsRule() {
		return getRegisteredClaimsAccess().getRule();
	}
	
	//enum EClaimType returns EClaimType:
	//                PRIVATE = 'PRIVATE' | PUBLIC = 'PUBLIC' | REGISTERED = 'REGISTERED';
	public EClaimTypeElements getEClaimTypeAccess() {
		return eEClaimType;
	}
	
	public EnumRule getEClaimTypeRule() {
		return getEClaimTypeAccess().getRule();
	}
	
	//OAuth2 returns OAuth2:
	//    {OAuth2} 'OAuth2.0';
	public OAuth2Elements getOAuth2Access() {
		return pOAuth2;
	}
	
	public ParserRule getOAuth2Rule() {
		return getOAuth2Access().getRule();
	}
	
	//BasicAuthentication returns BasicAuthentication:
	//    {BasicAuthentication} 'basicAuthentication';
	public BasicAuthenticationElements getBasicAuthenticationAccess() {
		return pBasicAuthentication;
	}
	
	public ParserRule getBasicAuthenticationRule() {
		return getBasicAuthenticationAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
