/*
 * generated by Xtext 2.27.0
 */
package org.ftn.domij.securitydsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.ftn.domij.securitydsl.services.SecurityDslGrammarAccess;
import security_dsl.Application;
import security_dsl.Attribute;
import security_dsl.Authentication;
import security_dsl.Database;
import security_dsl.Endpoint;
import security_dsl.JwtSecurity;
import security_dsl.OtherController;
import security_dsl.OtherModel;
import security_dsl.Private;
import security_dsl.Public;
import security_dsl.Role;
import security_dsl.Security_dslPackage;
import security_dsl.User;

@SuppressWarnings("all")
public class SecurityDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private SecurityDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == Security_dslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case Security_dslPackage.APPLICATION:
				sequence_Application(context, (Application) semanticObject); 
				return; 
			case Security_dslPackage.ATTRIBUTE:
				sequence_Attribute(context, (Attribute) semanticObject); 
				return; 
			case Security_dslPackage.AUTHENTICATION:
				sequence_Authentication(context, (Authentication) semanticObject); 
				return; 
			case Security_dslPackage.DATABASE:
				sequence_Database(context, (Database) semanticObject); 
				return; 
			case Security_dslPackage.ENDPOINT:
				if (rule == grammarAccess.getAuthEndpointRule()) {
					sequence_AuthEndpoint(context, (Endpoint) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getEndpointRule()) {
					sequence_Endpoint(context, (Endpoint) semanticObject); 
					return; 
				}
				else break;
			case Security_dslPackage.JWT_SECURITY:
				sequence_JwtSecurity(context, (JwtSecurity) semanticObject); 
				return; 
			case Security_dslPackage.OTHER_CONTROLLER:
				sequence_OtherController(context, (OtherController) semanticObject); 
				return; 
			case Security_dslPackage.OTHER_MODEL:
				sequence_OtherModel(context, (OtherModel) semanticObject); 
				return; 
			case Security_dslPackage.PRIVATE:
				sequence_Private(context, (Private) semanticObject); 
				return; 
			case Security_dslPackage.PUBLIC:
				sequence_Public(context, (Public) semanticObject); 
				return; 
			case Security_dslPackage.ROLE:
				sequence_Role(context, (Role) semanticObject); 
				return; 
			case Security_dslPackage.USER:
				sequence_User(context, (User) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Application returns Application
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         description=EString? 
	 *         app_database=Database? 
	 *         app_security=Security? 
	 *         app_models+=User? 
	 *         app_models+=Role? 
	 *         (app_models+=OtherModel app_models+=OtherModel*)? 
	 *         app_controllers+=Authentication? 
	 *         (app_controllers+=OtherController app_controllers+=OtherController*)?
	 *     )
	 * </pre>
	 */
	protected void sequence_Application(ISerializationContext context, Application semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Attribute returns Attribute
	 *
	 * Constraint:
	 *     (name=EString type=EType)
	 * </pre>
	 */
	protected void sequence_Attribute(ISerializationContext context, Attribute semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, Security_dslPackage.Literals.ATTRIBUTE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Security_dslPackage.Literals.ATTRIBUTE__NAME));
			if (transientValues.isValueTransient(semanticObject, Security_dslPackage.Literals.ATTRIBUTE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Security_dslPackage.Literals.ATTRIBUTE__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAttributeAccess().getNameEStringParserRuleCall_2_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getAttributeAccess().getTypeETypeEnumRuleCall_4_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AuthEndpoint returns Endpoint
	 *
	 * Constraint:
	 *     (url=EString function_name=EString method=EEndpointMethod)
	 * </pre>
	 */
	protected void sequence_AuthEndpoint(ISerializationContext context, Endpoint semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, Security_dslPackage.Literals.ENDPOINT__URL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Security_dslPackage.Literals.ENDPOINT__URL));
			if (transientValues.isValueTransient(semanticObject, Security_dslPackage.Literals.ENDPOINT__FUNCTION_NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Security_dslPackage.Literals.ENDPOINT__FUNCTION_NAME));
			if (transientValues.isValueTransient(semanticObject, Security_dslPackage.Literals.ENDPOINT__METHOD) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Security_dslPackage.Literals.ENDPOINT__METHOD));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAuthEndpointAccess().getUrlEStringParserRuleCall_1_0(), semanticObject.getUrl());
		feeder.accept(grammarAccess.getAuthEndpointAccess().getFunction_nameEStringParserRuleCall_3_0(), semanticObject.getFunction_name());
		feeder.accept(grammarAccess.getAuthEndpointAccess().getMethodEEndpointMethodEnumRuleCall_5_0(), semanticObject.getMethod());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Controller returns Authentication
	 *     Authentication returns Authentication
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         path=EString 
	 *         signup_endpoint=AuthEndpoint? 
	 *         login_endpoint=AuthEndpoint? 
	 *         logout_endpoint=AuthEndpoint? 
	 *         (controller_endpoints+=Endpoint controller_endpoints+=Endpoint*)?
	 *     )
	 * </pre>
	 */
	protected void sequence_Authentication(ISerializationContext context, Authentication semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Database returns Database
	 *
	 * Constraint:
	 *     (vendorName=EDatabaseType url=EString username=EString password=EString)
	 * </pre>
	 */
	protected void sequence_Database(ISerializationContext context, Database semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, Security_dslPackage.Literals.DATABASE__VENDOR_NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Security_dslPackage.Literals.DATABASE__VENDOR_NAME));
			if (transientValues.isValueTransient(semanticObject, Security_dslPackage.Literals.DATABASE__URL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Security_dslPackage.Literals.DATABASE__URL));
			if (transientValues.isValueTransient(semanticObject, Security_dslPackage.Literals.DATABASE__USERNAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Security_dslPackage.Literals.DATABASE__USERNAME));
			if (transientValues.isValueTransient(semanticObject, Security_dslPackage.Literals.DATABASE__PASSWORD) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Security_dslPackage.Literals.DATABASE__PASSWORD));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDatabaseAccess().getVendorNameEDatabaseTypeEnumRuleCall_1_0(), semanticObject.getVendorName());
		feeder.accept(grammarAccess.getDatabaseAccess().getUrlEStringParserRuleCall_3_0(), semanticObject.getUrl());
		feeder.accept(grammarAccess.getDatabaseAccess().getUsernameEStringParserRuleCall_5_0(), semanticObject.getUsername());
		feeder.accept(grammarAccess.getDatabaseAccess().getPasswordEStringParserRuleCall_7_0(), semanticObject.getPassword());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Endpoint returns Endpoint
	 *
	 * Constraint:
	 *     (url=EString function_name=EString method=EEndpointMethod)
	 * </pre>
	 */
	protected void sequence_Endpoint(ISerializationContext context, Endpoint semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, Security_dslPackage.Literals.ENDPOINT__URL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Security_dslPackage.Literals.ENDPOINT__URL));
			if (transientValues.isValueTransient(semanticObject, Security_dslPackage.Literals.ENDPOINT__FUNCTION_NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Security_dslPackage.Literals.ENDPOINT__FUNCTION_NAME));
			if (transientValues.isValueTransient(semanticObject, Security_dslPackage.Literals.ENDPOINT__METHOD) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Security_dslPackage.Literals.ENDPOINT__METHOD));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEndpointAccess().getUrlEStringParserRuleCall_2_0(), semanticObject.getUrl());
		feeder.accept(grammarAccess.getEndpointAccess().getFunction_nameEStringParserRuleCall_4_0(), semanticObject.getFunction_name());
		feeder.accept(grammarAccess.getEndpointAccess().getMethodEEndpointMethodEnumRuleCall_6_0(), semanticObject.getMethod());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Security returns JwtSecurity
	 *     JwtSecurity returns JwtSecurity
	 *
	 * Constraint:
	 *     (
	 *         mechanism=ESecurityMechanism 
	 *         signatureAlgorithm=EString 
	 *         issuer=EString 
	 *         expirationTime=EInt 
	 *         audience=EString 
	 *         security_claims+=Public? 
	 *         security_claims+=Public* 
	 *         security_claims+=Private? 
	 *         security_claims+=Private* 
	 *         secret=EString
	 *     )
	 * </pre>
	 */
	protected void sequence_JwtSecurity(ISerializationContext context, JwtSecurity semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Controller returns OtherController
	 *     OtherController returns OtherController
	 *
	 * Constraint:
	 *     (name=EString path=EString (controller_endpoints+=Endpoint controller_endpoints+=Endpoint*)?)
	 * </pre>
	 */
	protected void sequence_OtherController(ISerializationContext context, OtherController semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns OtherModel
	 *     OtherModel returns OtherModel
	 *
	 * Constraint:
	 *     (name=EString identifierName=EString identifierType=EType (model_attributes+=Attribute model_attributes+=Attribute*)?)
	 * </pre>
	 */
	protected void sequence_OtherModel(ISerializationContext context, OtherModel semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Claim returns Private
	 *     Private returns Private
	 *
	 * Constraint:
	 *     name=EString
	 * </pre>
	 */
	protected void sequence_Private(ISerializationContext context, Private semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, Security_dslPackage.Literals.CLAIM__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Security_dslPackage.Literals.CLAIM__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPrivateAccess().getNameEStringParserRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Claim returns Public
	 *     Public returns Public
	 *
	 * Constraint:
	 *     name=EString
	 * </pre>
	 */
	protected void sequence_Public(ISerializationContext context, Public semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, Security_dslPackage.Literals.CLAIM__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Security_dslPackage.Literals.CLAIM__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPublicAccess().getNameEStringParserRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns Role
	 *     Role returns Role
	 *
	 * Constraint:
	 *     (identifierName=EString identifierType=EType (model_attributes+=Attribute model_attributes+=Attribute*)?)
	 * </pre>
	 */
	protected void sequence_Role(ISerializationContext context, Role semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns User
	 *     User returns User
	 *
	 * Constraint:
	 *     (identifierName=EString identifierType=EType (model_attributes+=Attribute model_attributes+=Attribute*)?)
	 * </pre>
	 */
	protected void sequence_User(ISerializationContext context, User semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
