/*
 * generated by Xtext 2.27.0
 */
package org.ftn.domij.securitydsl.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.ftn.domij.securitydsl.services.SecurityDslGrammarAccess;

@SuppressWarnings("all")
public class SecurityDslSyntacticSequencer extends AbstractSyntacticSequencer {

	protected SecurityDslGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Application_ControllersKeyword_8_0_q;
	protected AbstractElementAlias match_Application_ModelKeyword_7_0_q;
	protected AbstractElementAlias match_JwtSecurity___PrivateClaimsKeyword_14_0_LeftSquareBracketKeyword_14_1_RightSquareBracketKeyword_14_4__q;
	protected AbstractElementAlias match_JwtSecurity___PublicClaimsKeyword_13_0_LeftSquareBracketKeyword_13_1_RightSquareBracketKeyword_13_4__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (SecurityDslGrammarAccess) access;
		match_Application_ControllersKeyword_8_0_q = new TokenAlias(false, true, grammarAccess.getApplicationAccess().getControllersKeyword_8_0());
		match_Application_ModelKeyword_7_0_q = new TokenAlias(false, true, grammarAccess.getApplicationAccess().getModelKeyword_7_0());
		match_JwtSecurity___PrivateClaimsKeyword_14_0_LeftSquareBracketKeyword_14_1_RightSquareBracketKeyword_14_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getJwtSecurityAccess().getPrivateClaimsKeyword_14_0()), new TokenAlias(false, false, grammarAccess.getJwtSecurityAccess().getLeftSquareBracketKeyword_14_1()), new TokenAlias(false, false, grammarAccess.getJwtSecurityAccess().getRightSquareBracketKeyword_14_4()));
		match_JwtSecurity___PublicClaimsKeyword_13_0_LeftSquareBracketKeyword_13_1_RightSquareBracketKeyword_13_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getJwtSecurityAccess().getPublicClaimsKeyword_13_0()), new TokenAlias(false, false, grammarAccess.getJwtSecurityAccess().getLeftSquareBracketKeyword_13_1()), new TokenAlias(false, false, grammarAccess.getJwtSecurityAccess().getRightSquareBracketKeyword_13_4()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Application_ControllersKeyword_8_0_q.equals(syntax))
				emit_Application_ControllersKeyword_8_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Application_ModelKeyword_7_0_q.equals(syntax))
				emit_Application_ModelKeyword_7_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_JwtSecurity___PrivateClaimsKeyword_14_0_LeftSquareBracketKeyword_14_1_RightSquareBracketKeyword_14_4__q.equals(syntax))
				emit_JwtSecurity___PrivateClaimsKeyword_14_0_LeftSquareBracketKeyword_14_1_RightSquareBracketKeyword_14_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_JwtSecurity___PublicClaimsKeyword_13_0_LeftSquareBracketKeyword_13_1_RightSquareBracketKeyword_13_4__q.equals(syntax))
				emit_JwtSecurity___PublicClaimsKeyword_13_0_LeftSquareBracketKeyword_13_1_RightSquareBracketKeyword_13_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     'controllers:'?
	 *
	 * This ambiguous syntax occurs at:
	 *     app_database=Database 'model:'? (ambiguity) (rule end)
	 *     app_models+=OtherModel ']' (ambiguity) (rule end)
	 *     app_models+=Role (ambiguity) (rule end)
	 *     app_models+=User (ambiguity) (rule end)
	 *     app_security=Security 'model:'? (ambiguity) (rule end)
	 *     description=EString 'model:'? (ambiguity) (rule end)
	 *     name=EString 'model:'? (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_Application_ControllersKeyword_8_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     'model:'?
	 *
	 * This ambiguous syntax occurs at:
	 *     app_database=Database (ambiguity) 'controllers:' 'auth:' app_controllers+=Authentication
	 *     app_database=Database (ambiguity) 'controllers:' 'other:' '[' app_controllers+=OtherController
	 *     app_database=Database (ambiguity) 'controllers:'? (rule end)
	 *     app_security=Security (ambiguity) 'controllers:' 'auth:' app_controllers+=Authentication
	 *     app_security=Security (ambiguity) 'controllers:' 'other:' '[' app_controllers+=OtherController
	 *     app_security=Security (ambiguity) 'controllers:'? (rule end)
	 *     description=EString (ambiguity) 'controllers:' 'auth:' app_controllers+=Authentication
	 *     description=EString (ambiguity) 'controllers:' 'other:' '[' app_controllers+=OtherController
	 *     description=EString (ambiguity) 'controllers:'? (rule end)
	 *     name=EString (ambiguity) 'controllers:' 'auth:' app_controllers+=Authentication
	 *     name=EString (ambiguity) 'controllers:' 'other:' '[' app_controllers+=OtherController
	 *     name=EString (ambiguity) 'controllers:'? (rule end)
	 
	 * </pre>
	 */
	protected void emit_Application_ModelKeyword_7_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('private-claims:' '[' ']')?
	 *
	 * This ambiguous syntax occurs at:
	 *     audience=EString ('public-claims:' '[' ']')? (ambiguity) 'signature:' 'secret:' secret=EString
	 *     security_claims+=Public ']' (ambiguity) 'signature:' 'secret:' secret=EString
	 
	 * </pre>
	 */
	protected void emit_JwtSecurity___PrivateClaimsKeyword_14_0_LeftSquareBracketKeyword_14_1_RightSquareBracketKeyword_14_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('public-claims:' '[' ']')?
	 *
	 * This ambiguous syntax occurs at:
	 *     audience=EString (ambiguity) 'private-claims:' '[' ',' security_claims+=Private
	 *     audience=EString (ambiguity) 'private-claims:' '[' security_claims+=Private
	 *     audience=EString (ambiguity) ('private-claims:' '[' ']')? 'signature:' 'secret:' secret=EString
	 
	 * </pre>
	 */
	protected void emit_JwtSecurity___PublicClaimsKeyword_13_0_LeftSquareBracketKeyword_13_1_RightSquareBracketKeyword_13_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
