<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="security_dsl" nsURI="http://www.example.org/security_dsl" nsPrefix="security_dsl">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Application">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="uniqueTableName uniqueControllerName uniqueControllerPath controllerPath controllerNotNamedUserRole validPort hasDatabaseForModel hasUserAndRoleModelsForController"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="uniqueTableName" value="self.app_models ->  isUnique(m | m.tableName.toLower())"/>
      <details key="uniqueControllerName" value="self.app_controllers -> isUnique(c | c.name)"/>
      <details key="uniqueControllerPath" value=" self.app_controllers -> isUnique(c | c.path) and self.app_controllers -> forAll(c | c.name.toLower() &lt;> c.path.toLower())"/>
      <details key="controllerPath" value="self.app_controllers -> forAll(c | c.path.at(1) = '/')"/>
      <details key="controllerNotNamedUserRole" value="not self.app_controllers -> exists(c | c.name.toLower() = 'user' or c.name.toLower() = 'role' or c.name.toLower() = 'usercontroller' or c.name.toLower() = 'rolecontroller')"/>
      <details key="validPort" value="self.port >= 1024 and self.port &lt;= 49151"/>
      <details key="hasDatabaseForModel" value="self.app_models -> isEmpty() or not self.app_database->isEmpty()"/>
      <details key="hasUserAndRoleModelsForController" value="self.app_controllers -> isEmpty() or (&#xA;&#x9;        self.app_models -> exists(m | m.oclIsTypeOf(User))&#xA;&#x9;        and&#xA;&#x9;        self.app_models -> exists(m | m.oclIsTypeOf(Role))&#xA;&#x9;    )"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="app_database" eType="#//Database"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="app_models" upperBound="-1"
        eType="#//Model" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="app_controllers" upperBound="-1"
        eType="#//Controller" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="app_security" eType="#//Security"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Security dsl generated application"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="group" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="rs.ac.uns.ftn"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="artifact" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="demo"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"
        defaultValueLiteral="8080"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="localhost"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="uniqueAttributeName uniqueCollumnName onlyOneIdentifier roleMustHaveStringAttribute roleCanHaveIdAndStringAttribute roleCantHaveAdditionalAttributes"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="uniqueAttributeName" value="self.model_attributes -> isUnique(a | a.name)"/>
      <details key="uniqueCollumnName" value="self.model_attributes -> isUnique(a | a.collumnName)"/>
      <details key="onlyOneIdentifier" value="self.model_attributes -> select(a | a.isIdentifier) -> size() = 1"/>
      <details key="roleMustHaveStringAttribute" value="self.oclIsTypeOf(Role) implies self.model_attributes -> exists(a | a.type = EType::_'String')"/>
      <details key="roleCanHaveIdAndStringAttribute" value="&#xA;&#x9;&#x9;    self.oclIsTypeOf(Role) implies&#xA;&#x9;&#x9;    (&#xA;&#x9;&#x9;        self.model_attributes -> select(a | a.type = EType::_'String' and a.isIdentifier = true) -> size() = 1 )&#xA;&#x9;&#x9;        or&#xA;&#x9;&#x9;    (&#xA;&#x9;&#x9;        self.model_attributes -> select(a | a.type = EType::_'String' and a.isIdentifier = false) -> size() = 1&#xA;&#x9;&#x9;&#x9;&#x9;and&#xA;&#x9;&#x9;        self.model_attributes -> select(a | a.isIdentifier = true) -> size() = 1&#xA;&#x9;&#x9;    )"/>
      <details key="roleCantHaveAdditionalAttributes" value="self.oclIsTypeOf(Role) implies self.model_attributes -> size() &lt;= 2"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model_attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Controller" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="uniqueEndpoints urlStartsWithForwardSlash authenticationLimits loginExistanceForLogout endpointLimits methodAllowedRegistration methodAllowedLogin methodAllowedLogout"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="uniqueEndpoints" value="self.controller_endpoints -> isUnique(e | e.functionName) and self.controller_endpoints -> isUnique(e | e.url)"/>
      <details key="urlStartsWithForwardSlash" value="self.controller_endpoints -> forAll(e | e.url.at(1) = '/')"/>
      <details key="authenticationLimits" value="&#xA;&#x9;&#x9;&#x9;self.oclIsTypeOf(Authentication) implies&#xA;&#x9;&#x9;    (&#xA;&#x9;&#x9;        self.controller_endpoints -> select(e | e.type = EEndpointType::REGISTRATION) -> size() &lt;= 1&#xA;&#x9;&#x9;        and&#xA;&#x9;&#x9;        self.controller_endpoints -> select(e | e.type = EEndpointType::LOGIN) -> size() &lt;= 1&#xA;&#x9;&#x9;        and&#xA;&#x9;&#x9;        self.controller_endpoints -> select(e | e.type = EEndpointType::LOGOUT) -> size() &lt;= 1&#xA;&#x9;&#x9;    ) "/>
      <details key="loginExistanceForLogout" value="&#xA;&#x9;&#x9;    self.controller_endpoints -> select(e | e.type = EEndpointType::LOGOUT) -> size() = 1 implies&#xA;        &#x9;self.controller_endpoints -> select(e | e.type = EEndpointType::LOGIN) -> size() = 1"/>
      <details key="endpointLimits" value="&#xA;&#x9;&#x9;&#x9;not self.oclIsTypeOf(Authentication) implies&#xA;&#x9;&#x9;    (&#xA;&#x9;&#x9;        self.controller_endpoints -> select(e | e.type = EEndpointType::REGISTRATION) -> isEmpty()&#xA;&#x9;&#x9;        and&#xA;&#x9;&#x9;        self.controller_endpoints -> select(e | e.type = EEndpointType::LOGIN) -> isEmpty()&#xA;&#x9;&#x9;        and&#xA;&#x9;&#x9;        self.controller_endpoints -> select(e | e.type = EEndpointType::LOGOUT) -> isEmpty()&#xA;&#x9;&#x9;    )"/>
      <details key="methodAllowedRegistration" value="&#xA;        &#x9;self.controller_endpoints -> select(e | e.type = EEndpointType::REGISTRATION and (e.method = EEndpointMethod::POST or e.method->isEmpty())) -> size() &lt;= 1"/>
      <details key="methodAllowedLogin" value="&#xA;        &#x9;self.controller_endpoints -> select(e | e.type = EEndpointType::LOGIN and (e.method = EEndpointMethod::PUT or e.method = EEndpointMethod::DELETE)) -> size() = 0"/>
      <details key="methodAllowedLogout" value="&#xA;        &#x9;self.controller_endpoints -> select(e | e.type = EEndpointType::LOGOUT and (e.method = EEndpointMethod::PUT or e.method = EEndpointMethod::DELETE)) -> size() = 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controller_endpoints" upperBound="-1"
        eType="#//Endpoint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Security" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Database">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vendorName" lowerBound="1"
        eType="#//EDatabaseType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EDatabaseType">
    <eLiterals name="PostgreSQL"/>
    <eLiterals name="Oracle" value="1"/>
    <eLiterals name="MySQL" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ESecuirtyMechanism">
    <eLiterals name="JWT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//EType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isIdentifier" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collumnName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role" eSuperTypes="#//Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="role_instances" upperBound="-1"
        eType="#//RoleInstance" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User" eSuperTypes="#//Model"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EType">
    <eLiterals name="String" value="1"/>
    <eLiterals name="Float" value="2"/>
    <eLiterals name="Long" value="3"/>
    <eLiterals name="Integer" value="4"/>
    <eLiterals name="char" value="5"/>
    <eLiterals name="Boolean" value="6"/>
    <eLiterals name="boolean" value="7"/>
    <eLiterals name="Double" value="8"/>
    <eLiterals name="DateTime" value="9"/>
    <eLiterals name="Date" value="10"/>
    <eLiterals name="int"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleInstance">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Authentication" eSuperTypes="#//Controller"/>
  <eClassifiers xsi:type="ecore:EClass" name="Endpoint">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="uniqueRoleAuthorities"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="uniqueRoleAuthorities" value="self.role_authorities -> isUnique(r | r.name)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" eType="#//EEndpointMethod"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//EEndpointType"
        defaultValueLiteral="OTHER"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="role_authorities" upperBound="-1"
        eType="#//RoleInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EEndpointMethod">
    <eLiterals name="GET"/>
    <eLiterals name="POST" value="1"/>
    <eLiterals name="PUT" value="2"/>
    <eLiterals name="DELETE" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EEndpointType">
    <eLiterals name="REGISTRATION"/>
    <eLiterals name="LOGIN" value="1"/>
    <eLiterals name="LOGOUT" value="2"/>
    <eLiterals name="OTHER" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JWT" eSuperTypes="#//Security">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="uniqueClaims registeredClaimSubject singleRegisteredClaim"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="uniqueClaims" value="self.jwt_claims -> isUnique(c | c.name)"/>
      <details key="registeredClaimSubject" value="&#xA;&#x9;&#x9;    self.jwt_claims -> forAll(c | c.name = 'subject' implies c.type = EClaimType::REGISTERED)"/>
      <details key="singleRegisteredClaim" value="&#xA;&#x9;        self.jwt_claims -> select(c | c.type = EClaimType::REGISTERED and c.name = 'subject') -> size() &lt;= 1&#xA;&#x9;        and&#xA;&#x9;        self.jwt_claims -> select(c | c.type = EClaimType::REGISTERED) -> size() &lt;= 1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="signatureAlgorithm" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="secret" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="somesecret"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jwt_claims" upperBound="-1"
        eType="#//Claim" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="registeredclaims" lowerBound="1"
        eType="#//RegisteredClaims" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Claim">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="uniqueClaimAttribute"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="uniqueClaimAttribute" value="Claim.allInstances() -> isUnique(c | c.claim_attribute)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//EClaimType"
        defaultValueLiteral="PRIVATE"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="claim_attribute" lowerBound="1"
        eType="#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EClaimType">
    <eLiterals name="PRIVATE"/>
    <eLiterals name="PUBLIC" value="1"/>
    <eLiterals name="REGISTERED" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegisteredClaims">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="expirationTimeGreaterThanZero"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="expirationTimeGreaterThanZero" value="self.expirationTime > 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expirationTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="issuer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="audience" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="WEB"/>
  </eClassifiers>
</ecore:EPackage>
