/*
 * generated by Xtext 2.27.0
 */
package org.xtext.securitydsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSecurityDslScopeProvider extends DelegatingScopeProvider {
}
