/*
 * generated by Xtext 2.27.0
 */
package org.ftn.domi.securitydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.ftn.domi.securitydsl.parser.antlr.internal.InternalSecurityDslParser;
import org.ftn.domi.securitydsl.services.SecurityDslGrammarAccess;

public class SecurityDslParser extends AbstractAntlrParser {

	@Inject
	private SecurityDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSecurityDslParser createParser(XtextTokenStream stream) {
		return new InternalSecurityDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Application";
	}

	public SecurityDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SecurityDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
